### ISSUE TITLE
SqlSpatial

### ISSUE THREAD

**Issue by dotMorten** [dotnet/SqlClient#1]
Will this repo also include the native source for SqlSpatial, so we can cross compile it and get proper support for these types on Android/iOS/ etc?

**Comment by David-Engel** [comment]
I assume you mean the namespaces System.Data.Spatial and System.Data.Objects.SqlClient (containing SqlSpatialFunctions).

No. Spatial is still an existing feature gap between Framework and Core and not one we've targeted as part of this project. We do realize it is still a gap that needs to be filled, though. I don't have any insight for when that might happen.

**Comment by dotMorten** [comment]
I meant SqlGeometry, SqlGeography, SqlHierachy etc from the Microsoft.SqlServer.Types package

**Comment by David-Engel** [comment]
Ah, okay. Same answer, though. We haven't brought anything spatial related into this project.

**Comment by dotMorten** [comment]
😢

**Comment by divega** [comment]
@dotMorten, the SQL Server team is aware of this feature request and and we will continue discussing with them about bringing Microsoft.SqlServer.Types forward. What can help at this point is to collect concrete data on customers that are blocked from moving their applications because this feature isn't supported in .NET Core, or because it isn't available cross-platform. 

Also (@David-Engel, feel free to correct me if I am wrong), I believe when using Microsoft.Data.SqlClient on .NET Framework, the functionality is enabled, just like it is in System.Data.SqlClient on .NET Framework.

**Comment by David-Engel** [comment]
@divega I'm unfamiliar with Microsoft.SqlServer.Types but I don't see any dependencies on S.D.SqlClient, so I would assume it works the same with either one, too.

**Comment by Wraith2** [comment]
@dotMorten a similar question came up from the EFCore repo and in order to permit users to work around this problem https://github.com/dotnet/corefx/pull/36678 was added which will allow you to serialize your spatial types in code and pass them through to sql as binary representations directly. That fix should/will be included in this project.

**Comment by dotMorten** [comment]
One of the big problems here is these UDT types doesn't "just work", as the assembly info doesn't match anything client side (assembly name, version and public key must match). otherwise you're left with having to pull out the SqlBinary and parse it yourself. And even after that point you still don't have the same math available to perform the same operations you can perform in SQL server side. It's a really ugly story for a type that's quite literally built into SqlServer.

**Comment by MaceWindu** [comment]
@David-Engel 
>I don't see any dependencies on S.D.SqlClient

but it is. Check my write-up [here](https://github.com/linq2db/linq2db/pull/1929#issuecomment-541396922)
