### ISSUE TITLE
System.Data.SqlClient.SqlInternalConnectionTds constructor purges original call stack when rethrowing an exception

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/SqlClient#100]
`System.Data.SqlClient.SqlInternalConnectionTds` currently goes like this:

```
try
{
    OpenLoginEnlist(timeout, connectionOptions, redirectedUserInstance);
    break;
}
catch (SqlException sqlex)
{
    if (something)
    {
         throw sqlex;
    }
```

`throw sqlex` causes original call stack of where the exception was thrown to be lost. If that's what it desired then it should be explained, otherwise just use `throw;`

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by GSPP** [comment]
It is important that internal stack information is not destroyed. This is very valuable when guessing the source of bugs. `throw;` is correct.

I have never seen code that intentionally deletes part of the stack in order to make it easier to interpret the stack. The entire framework does not do this. This would not be a good choice.
