### ISSUE TITLE
sqlclient does not close connections in Docker(debian)

### ISSUE THREAD

**Issue by paalmoest** [dotnet/SqlClient#104]
We are seeing behaviour form the System.Data.Sqlclient is not closing the connections when its running  on the official mircosoft/dotnet docker image for linux. The connections are accumulating to over 400 connections in a couple of days on a service with little traffic. We have the same code running on a windows platform and there we do not see this behaviour. 
We are running dotnet 1.1.0.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by divega** [comment]
@saurabh500 are you confident that this issue is fixed or something the SqlClient team should investigate further? 

I see customers reporting that it is fixed but also one customer saying it wasn't for him, at https://github.com/dotnet/SqlClient/issues/104#issuecomment-326533008 and also https://github.com/dotnet/corefx/issues/13422#issuecomment-326532463.

**Comment by David-Engel** [comment]
Assigning to @saurabh500 to confirm if the fix is already in.

**Comment by dbeaulieu** [comment]
I'm experiencing this issue as well for an app being migrated to docker+kubernetes.  The app typically has ~30 connections open but that number surges to ~200 at times.  The app is behind a load balancer and the windows version serving the same traffic uses < 10 connections.  

Environment info:
`<PackageReference Include="System.Data.SqlClient" Version="4.6.1" />`
`FROM mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9`

> OS-IMAGE                       KERNEL-VERSION   CONTAINER-RUNTIME
> Debian GNU/Linux 9 (stretch)   4.9.0-9-amd64    docker://18.6.3

**Comment by cheenamalhotra** [comment]
@paalmoest 

Although this is an old issue, I'm trying to regain the context. Could you confirm if the issue still exists and if yes, is it related to #129 ?

**Comment by cheenamalhotra** [comment]
@saurabh500 

Could you confirm if the fix you mentioned above in comment https://github.com/dotnet/SqlClient/issues/104#issuecomment-299057506 made it to the driver? Or it was only added to servicing branch? Please point us to the PR that was merged to address this issue.

Curious as @dbeaulieu reported this issue with S.D.S v4.6.1. We should consider moving it over to S.D.S and M.D.S if it didn't get merged in corefx - 'master' branch.

**Comment by saurabh500** [comment]
https://github.com/dotnet/corefx/commit/2e7be0c790fb89411939817ab279f287dbc29eda

According to the process, this fix was first made to master and then ported to servicing branch.

**Comment by saurabh500** [comment]
I also see the fix made for the issue in dotnet/SqlClient repo 
https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs#L62-L66

**Comment by saurabh500** [comment]
@cheenamalhotra  do we have a repro at our end for this bug ?

**Comment by saurabh500** [comment]
I cannot reproduce this issue with Sync Connection.Open(), however with SqlConnection.OpenAsync executed 300 times on different tasks, makes some of the connections to leak through. I have a repro posted at https://github.com/saurabh500/sqlclientrepros/tree/master/connectionleak

The async connection paths need to be investigated here.

**Comment by saurabh500** [comment]
Update, I see TCP connections lingering around and they are being reused for subsequent connections and operations. The connection pool has a logic to clear out the connections that have been returned to the pool via SqlConnection.Close()/Dispose() after a time period of 3-5 minutes. 

If I wait for 5 minutes these connections are killed. 

Since there is no concrete repro for this issue, I am going to close. Please comment with a repro that can be used to show the problem. 

As far as the original issue was concerned, the TcpStream was not disposed by SqlClient making the connections linger for a really long time. That issue was fixed quite some time ago as I have mention above.
