### ISSUE TITLE
Handling infinite loops / out of memory exceptions when running SqlCommands 

### ISSUE THREAD

**Issue by malhotrar** [dotnet/SqlClient#1183]
I develop an ETL system that allows users to run SQL scripts (and a lot of other things) powered by .NET for my organization. Recently we have had a few instances where users have managed to hit out of memory exceptions by running a query using code like the following:

```
using (var conn = new SqlConnection())
	{
		conn.Open();

		var cmd = @"WHILE (1 = 1) BEGIN SELECT 1 / 0 END";

		using (var command = new SqlCommand(cmd, conn))
		{
			command.ExecuteNonQuery();
		}
	}
```

This toy example is easy to prevent by simply prepending "SET XACT_ABORT ON;" to every script run as such:

```
using (var conn = new SqlConnection())
	{
		conn.Open();

		var cmd = @"SET XACT_ABORT ON; WHILE (1 = 1) BEGIN SELECT 1 / 0 END";

		using (var command = new SqlCommand(cmd, conn))
		{
			command.ExecuteNonQuery();
		}
	}
```

However, this quickly fails once someone does something like (which people have):

```
using (var conn = new SqlConnection())
	{
		conn.Open();

		var cmd = @"SET XACT_ABORT ON; WHILE (1 = 1) PRINT 'running' END";

		using (var command = new SqlCommand(cmd, conn))
		{
			command.ExecuteNonQuery();
		}
	}
```

I have discovered that setting 'FireInfoMessageEventOnUserErrors' on the connection object avoids the out of memory exception, however, makes it such that I have to throw the SqlException myself.

```
using (var conn = new SqlConnection(...)){
		conn.Open();
		
		conn.FireInfoMessageEventOnUserErrors = true;

		Exception ex = null;

		conn.InfoMessage += (o, e) =>
		{
			if (e.Errors.Count > 0)
			{
				ex = CreateSqlException(e.Errors);
			} else {
				ex = null;
			}
		};

		var cmd = @"SET XACT_ABORT ON; WHILE (1 = 1) BEGIN SELECT 1 / 0 END";
		
		using (var command = new SqlCommand(cmd, conn)){
			command.ExecuteNonQuery();
			if (ex != null){
				throw ex;
			}
		}
	}

public static SqlException CreateSqlException(SqlErrorCollection errors)
{
	Exception innerEx = null;
	var c = typeof(SqlErrorCollection).GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance);
	SqlException ex = (Activator.CreateInstance(typeof(SqlException), BindingFlags.NonPublic | BindingFlags.Instance, null, new object[] { errors[0].Message, errors,
	  innerEx, Guid.NewGuid() }, null) as SqlException);
	return ex;
}
```

Is this the right way to think about solving this problem? Are there any other suggestions / pitfalls of constructing code this way?

**Comment by Wraith2** [comment]
Why does fire info message fix the issue? What message do you get that causes the callback to fire and is specific enough to only prevent OOMs?

**Comment by malhotrar** [comment]
@Wraith2  - here is more detail, with some of my hypothesis; I guess I'm looking for answers to the questions you asked from this group.

The following will never print anything (because it seems like its holding on all its messages until the statement completes, which it never will because of OOM.

```
using (var conn = new SqlConnection(@"..."))
	{
		conn.Open();

		conn.InfoMessage += (o, e) =>
		{
			// Never prints and hits an out of memory exception
			Console.WriteLine(e);
		};

		var cmd = @"WHILE (1 = 1) BEGIN Print 'hello' END";

		using (var command = new SqlCommand(cmd, conn))
		{
			command.ExecuteNonQuery();
		}
	}
```
My observation is that the info message handler is only fired once a statement completes, which means that the above prints are held in memory forever, and either hit a limit on an array size, inducing an OOM. I'm using Linqpad as my playground right now - and I don't get much more than:

OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

(For memory-intensive queries, download the AnyCPU version of LINQPad for 64-bit support at www.linqpad.net.)

The following does print both messages but never terminates even if an error is encountered, because its now simply an info message.

```
using (var conn = new SqlConnection(@"..."))
	{
		conn.Open();

		conn.FireInfoMessageEventOnUserErrors = true;
		conn.InfoMessage += (o, e) =>
		{
			// Prints but will never throw
			Console.WriteLine(e);
		};

		var cmd = @"WHILE (1 = 1) BEGIN PRINT 'hello'; SELECT 1/0; END";

		using (var command = new SqlCommand(cmd, conn))
		{
			command.ExecuteNonQuery();
		}
	}
```

**Comment by JRahnama** [comment]
@malhotrar regarding the issue before going to Info message part,  Remember When SET XACT_ABORT is ON, if a Transact-SQL statement raises a run-time error, the entire transaction is terminated and rolled back, however when When SET XACT_ABORT is OFF, in some cases only the Transact-SQL statement that raised the error is rolled back and the **transaction continues processing**. 

It could be reviewed in [Microsoft Docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-xact-abort-transact-sql?view=sql-server-ver15).

`DECLARE @XACT_ABORT VARCHAR(3) = 'OFF';
IF ( (16384 & @@OPTIONS) = 16384 ) SET @XACT_ABORT = 'ON';
SELECT @XACT_ABORT AS XACT_ABORT;`

will show current setting on your server.
I have also tested with SSMS (which uses System.Data.SqlClient) and it acts the same as you mentioned.

I think stating try/catch block in query statement will fix the issue as well. Something like:
```
BEGIN TRY
WHILE (1 = 1) BEGIN SELECT 1 / 0 END
END TRY
BEGIN CATCH 
THROW
END CATCH
```

In my opinion this or the way you have handled it raises the exception on the server and it notifies the driver right away.
I will look into what happens when `FireInfoMessageEventOnUserErrors` is called.

Also keep that in mind that TRY block causes a transaction to enter an uncommittable state when the error occurs inside a TRY block. An uncommittable transaction can only perform read operations or a ROLLBACK TRANSACTION.

Could be reviewed [here](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/try-catch-transact-sql?view=sql-server-ver15#uncommittable-transactions-and-xact_state).

**Comment by malhotrar** [comment]
@JRahnama - completely hear you on the try/catch - the issue here is that I own an ETL engine for a SaaS platform that is responsible for running scripts written by our consultants to configure instances for the clients they consult with. I'd be uncomfortable adding any logic outside of XACT_ABORT to their batches as I obviously have no context or understanding of the code they write. I am simply trying to understand what is the best approach to avoid an OOM exception if someone has a print statement inside an infinite loop.

**Comment by JRahnama** [comment]
@malhotrar to answer your question I think the best approach is the one you have chosen, SET XACT_ABORT ON as you mentioned since it works on the server side, you will also need to have a try/catch block in your code in order to catch the exception. Another approach would be using of `FireInfoMessageEventOnUserErrors`.

More explanation:
The OOM exception happens as the server sends the error 8134 with severity 16, anything above severity 17 will cause the server to stop the process, therefore this goes on in this case. So this situation will not come up with higher severity problems. 

Why this does not happen at `FireInfoMessageEventOnUserErrors`:

> When you set FireInfoMessageEventOnUserErrors to true, errors that were previously treated as exceptions are now handled as InfoMessage events. All events fire immediately and are handled by the event handler. 

you can read more about `FireInfoMessageEventOnUserErrors` at [MS documentation](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.fireinfomessageeventonusererrors?view=dotnet-plat-ext-5.0).

If your question is answered feel free to close the issue.

Thanks.

**Comment by malhotrar** [comment]
@JRahnama  - thanks for the confirmation of approach. This completely makes sense and aligns with my observations.
