### ISSUE TITLE
Test System.Data.Tests.SqlTypes.SqlDoubleTest.Conversions fails on non english culture

### ISSUE THREAD

**Issue by satano** [dotnet/SqlClient#120]
The test is failing on [this line](https://github.com/dotnet/corefx/blob/444e6bb7fd274be680fb3bf4b22258821e77ae2c/src/System.Data.Common/tests/System/Data/SqlTypes/SqlDoubleTest.cs#L408) (and I believe [this will be the same](https://github.com/dotnet/corefx/blob/444e6bb7fd274be680fb3bf4b22258821e77ae2c/src/System.Data.Common/tests/System/Data/SqlTypes/SqlDoubleTest.cs#L413)).

Failing message is:

> Assert.Equal() Failure
> Expected: 6.4E+65
> Actual:   6,4E+65

The value is the same, but notice the **difference in decimal separator**. My Windows' culture is Slovak and we have comma as a decimal separator. The method of `SqlDouble.ToString()` and its conversion to `SqlString` is done without specifying the culture, so it uses the system's one, hence the difference.

**Comment by initram** [comment]
I think this should have been moved to the dotnet/runtime repo, but it seems that the issue does not exist there anymore.
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Data.Common/tests/System/Data/SqlTypes/SqlDoubleTest.cs#L274
They are now using ToString on a double literal instead of using a string literal, this will ensure that the string has the correct format for the local culture.

So I think this case can just be closed.

**Comment by cheenamalhotra** [comment]
Great, thanks @initram !
