### ISSUE TITLE
Query execution speed is 2-3 times slower whenever dotnet-counters is connected to an app

### ISSUE THREAD

**Issue by vonzshik** [dotnet/SqlClient#1252]
[Repro](https://github.com/vonzshik/SqlClientCounters).

After the app is started, put in the console:

```
dotnet-counters monitor --counters "Microsoft.Data.SqlClient.EventSource" -n SqlClientCounters
```

For me, rps drops from 17k to 7k.  The moment dotnet-counters is closed, everything comes to normal.
No such thing for Npgsql. You can try this out by putting this in the console:

```
dotnet-counters monitor --counters "Npgsql" -n NpgsqlCounters
```

Microsoft.Data.SqlClient 3.0
Windows 10

**Comment by Wraith2** [comment]
Is the volume of reported events about the same between the two? 
IMO we've got a lot of events in sqlclient but I don't know how much npgsql reports, it could be a bulk data problem.

**Comment by vonzshik** [comment]
Actually, it's pretty much 0 events on npgsql's side. I took a closer look, and it seems the problem is due to counters being in the same class as events. So the moments counters are enabled, the same things happen for events. Npgsql uses a different class (and even then, there is only 2 events).

**Comment by Wraith2** [comment]
@roji the obvious way to fix this issue is to add lots of events and counters to npgsql so that the speed decrease is equivalent 😀 

I'll take a look at the repro and see if there's anything that can clearly be improved. As I mentioned SqlClient outputs a huge amount of events because they're an excellent live debugging aid so it's unlikely that anything can be entirely removed. Splitting counters and events may be possible.

**Comment by roji** [comment]
Makes sense @Wraith2, thanks. Splitting counters and events does seem like the obvious thing to do, but I have to admit that taking a 30% hit just because events are turned on seems... excessive :) Maybe there's a way to be more pay-per-play, i.e. only do the heavy stuff only when the appropriate event is actually subscribed to, or something similar.

**Comment by DavoudEshtehari** [comment]
Event counters values are calculating even without monitoring with the lowest perf impact, which means the big difference could come from the number of events to be logged or showed up.

**Comment by roji** [comment]
@DavoudEshtehari it's very unlikely the perf issue is related to the counters (calculating them is very trivial), but rather to unrelated events in the same class.

**Comment by Wraith2** [comment]
I don't see any reason from the code that the events and counters can't be split into separate classes, I'd suggest `Microsoft.Data.SqlClient.EventSource` for the tracing events and `Microsoft.Data.SqlClient.EventCounters` for the counters to allow independent use. That's a policy decision @David-Engel @cheenamalhotra .

**Comment by roji** [comment]
That would definitely fix things for counters, but this kind of slowdown seems problematic for the events as well - I'd recommend trying to look at why it's so much regardless of counters. It's possible that if the events are made more pay-per-play, the counters would also becomes completely cheap and splitting the type wouldn't be necessary (but all this is just speculation).

**Comment by Wraith2** [comment]
Events, at least in this library, are used as a way to trace the activity of the entire library for tracing of problems in release environments. They are a primary source of debugging information for support of the library. The library is heavily instrumented with events and if you turn them all on it generates a huge amount of information. 

In my testing I'm getting an extra 1Gib per minute of memory throughput and I'm not even looking at the data I just turned on the events and let them drop immediately to GC. Almost all of that data is strings and the methods required to format it consume some additional time but <1% in my profiles. The memory overhead is unavoidable because we want and need rich data and the cpu overhead isn't too bad. We could optimize the string formatting using advance span and buffer trickery for netcore or later runtimes but I don't believe the return on investment is particularly compelling for doing so. Unless you are debugging the library the trace information will be largely unusable.

Splitting counters out so that things users will commonly want to access as part of monitoring activities makes sense and can be done. Reducing the overhead of generating all the events from the library isn't likely to gain much speed back and will require disproportionate effort for the gain. If users want to use events they should be careful to subscribe only to the events they need.

**Comment by roji** [comment]
Thanks for the info.

In my mind, there's trace logging/diagnostics which you'd only ever turn off in local debugging or similar, and then there's normal diagnostics which is meant to be suitable for a production system. For example, it's perfectly reasonable for users to want to (permanently!) track their web application in AppInsights or any other consumer of diagnostics - just like it's reasonable to turn on event counters on a production system.

If the huge perf penalty discussed only pertains to some sort of tracing that is never meant to be used in production, then sure. However, if, in order to get any events in production, an application cannot run with diagnostics/AppInsights in production without this kind of penalty, then I think there's a pretty severe issue.

I'm not familiar with how SqlClient approaches tracing/diagnostics, so I may be wide off the mark here. I'm just trying to make sure users can turn on reasonable diagnostics in production without their application suffering a major perf degradation.

**Comment by Wraith2** [comment]
> In my mind, there's trace logging/diagnostics which you'd only ever turn off in local debugging or similar, and then there's normal diagnostics which is meant to be suitable for a production system. 

If there needs to be a split of production debugging data and production monitoring data that can be done if we can identify what people want to see in which scenario. Perhaps it just needs some guidance on which events to use in production? For example the SNI events are worthless unless you're debugging but things like ExecuteReader start and finish are quite valuable for continuous monitoring.

The current and long term historic configuration for events in this library is for debug tracing and if you turn on everything you'll see a lot of data and take the perf hit that it generates. It's another aspect of being a very old codebase, it predates the current common use of events for casual production monitoring.

I'd say first step split out the counters. Then investigate what users are trying to get out of events, if anything, and make that as low profile as possible without degrading the ability to use rich events for support. Does that seem reasonable? If so how would we go about identifying users needs from events?

**Comment by roji** [comment]
> For example the SNI events are worthless unless you're debugging but things like ExecuteReader start and finish are quite valuable for continuous monitoring.

Definitely agree. I'd generally expect this to be pay-per-play, i.e. if I subscribe to an event, I'm opting into paying the perf penalty needed to produce it - but without paying for other events I'm not interested in. A pay-per-play approach may also remove the need to define debugging vs. production - just try to make sure no work is done for a thing unless that thing is opted into.

> I'd say first step split out the counters.

Sure, that sounds reasonable - we can spin off the events perf to a separate issue and keep this one for the counters, for sure.

**Comment by cheenamalhotra** [comment]
Following up on this issue, 
@vonzshik could you provide us repro code that you are using to measure performance?

**Comment by vonzshik** [comment]
@cheenamalhotra [here](https://github.com/vonzshik/SqlClientCounters). 

After the app is started, just call `dotnet-counters monitor -n SqlClientCounters --counters "Microsoft.Data.SqlClient.EventSource"` at some point and you're gonna see the cliff immediately.

**Comment by Zoxive** [comment]
There must be something else going on in play here. Using the repo steps I see no difference in RPS.

(I was curious for myself what the over-head would be for using dotnet-counters was against our environments)

**Comment by vonzshik** [comment]
@Zoxive definitely not imagining this
![image](https://user-images.githubusercontent.com/14861420/141327444-3ea0631a-0eff-4928-9e99-46688d3e36f0.png)

**Comment by Zoxive** [comment]
Same works here everytime.

![image](https://user-images.githubusercontent.com/124676/141330368-9423e9ff-b509-4c9d-8916-a77b027b835e.png)

What dotnet-counters version do you have?
Heres mine:

```
F:\Utilities>dotnet-counters.exe --version
5.0.251802+592990b5913930a1b51b7505cdbb3b2205c79f03
```

**Comment by vonzshik** [comment]
5.0.227602+f3ffe27acd2739518d359da0284ae6bf9e9e7966

**Comment by vonzshik** [comment]
Huh, that's interesting - just updated dotnet-counters to the latest version and now it works correctly. So, that actually was a dotnet-counters bug, and not SqlClient's one. @Zoxive thanks!

I'm closing this issue since it doesn't look like there is anything to fix.
