### ISSUE TITLE
SqlConnectionStringBuilder dictionary error from multiple threads

### ISSUE THREAD

**Issue by j-hicks** [dotnet/SqlClient#128]
When access from multiple threads, the SqlConnectionStringBuilder class now throws the following error: 

> “Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.”

A change to the dictionary class was implemented a year ago that raises this error (see [issue 31186](https://github.com/dotnet/corefx/issues/31186)). 

In my case, the SqlConnectionStringBuilder is created statically from configuration values, but the first connection string request may not be on the startup thread. This seems to be what generates this error.

I suggest a simple replacement of the Dictionary with a ConcurrentDictionary. I may submit a pull request to address this, unless someone else wants to take this.

**Comment by divega** [comment]
@j-hicks I agree with @Wraith2.  SqlConnectionStringBuilder isn't and never was thread safe. If you are getting this exception since now, there is likely a bug in the way you are using it that before you just didn't know about.

**Comment by j-hicks** [comment]
Of course we all agree that the existing version isn't thread-safe, and probably never was.
In my case, I didn't realize that this would be an issue until the “throw” — recently added to the Dictionary class — alerted me to the problem.

The real question is whether it _should_ be thread-safe. Given that the most likely use case is configuration data which is shared across an application (i.e. a singleton instance handling both set’s and get’s which may be accessed across a multi-threaded application), it seems to me that the answer is “yes”.

I rewrote my own code already to consume this class use of this without a shared instance, so this is not urgent for me. I believe the existing class could be easily modified to accommodate this, but I haven't tried yet, and I won’t bother unless there’s value in implementing the change.

**Comment by roji** [comment]
@j-hicks the class could be easily changed, but this is less about what SqlConnectionStringBuilder does specifically, and more about what kind of guarantees DbConnectionStringBuilder provides in general. In other words, other providers would also have to modify their connection string builders, or we start to have divergent implementations, and code being ported from one builder fails (in potentially subtle ways!) on another.

In addition, the general approach in .NET is to not make classes thread-safe unless there's a specific, good reason to do so - non-thread-safe is the default. This doesn't seem to be the case here; a connection string builder isn't typically meant to be modified concurrently, but rather a single instance is usually instantiated and used to generated a connection string. At that point the connection string can be used by all parts of the program.

Note that read-only concurrent reads should be fine - the problem is with concurrent mutation.

**Comment by j-hicks** [comment]
Ok.
Frankly, I can’t explain why I got the error, since I didn’t think I set values from multiple places. The problem was intermittent and rare, and therefore extremely hard to reproduce. I suspect that it had something to do with using the Polly library for automatic retries, but I can't prove it.

If no one thinks that this is worthwhile, I'm happy to go do something else. As I mentioned, it wasn't hard to rewrite my code to ensure single-threaded access, and I'm sure others can do the same.

@roji I appreciate your work on Npgsql! I have used it extensively in my own contribution. You may be interested in my sharding-capable, high-performance ORM, at [https://www.argentsea.com](https://www.argentsea.com). I would love to hear your thoughts!

Unless someone can suggest a justification to keeping this open, I'll find other fish to fry.

Thanks all!

**Comment by roji** [comment]
@j-hicks thanks for understanding and also for the kind words! I didn't know about ArgentSea, will note it and try to take a look (although times are extremely busy at the moment so it may take a while).

If you have any other thoughts about ADO.NET or SqlClient (or Npgsql) please don't hesitate to share them.
