### ISSUE TITLE
Authenticate .NET Core Client of SQL Server with Integrated Security from Linux Docker Container

### ISSUE THREAD

**Issue by Grey007** [dotnet/SqlClient#143]
Hi all, 

I have a core application running in a linux docker container, on a linux vm. 

I need a way for my core application to connect out a SQL Server on a Windows Server (Enterprise) using Integrated Security as we're not allowed to do it via username and passwords. The only thing that sort of works is the following tutorial:
https://www.codeproject.com/Articles/1272546/Authenticate-NET-Core-Client-of-SQL-Server-with-In

But really isn't clean. Considering that you have to constantly refresh the Kerberos ticket. 

Any suggestions on how to do this cleaner?

**Comment by cheenamalhotra** [comment]
Hi @Grey007 

Currently Integrated Security based Authentication with Native library is supported only on Windows, and the driver does not support NTLM Authentication.

We have no plans to support NTLM Authentication in SqlClient as it's insecure and deprecated now. Kerberos is more advanced and secure way of authentication, and always recommended.

There is also an option of [MSI Authentication](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) if your client machine is hosted in Azure Resource Manager, in which Managed Service Identity (MSI) access tokens can be generated and passed to the driver for creating connection without the need to pass credentials.

**Comment by cheenamalhotra** [comment]
Hi @Grey007 

Do you have any further questions?

**Comment by Grey007** [comment]
Nope, it's not great and a solution will need to be found.

**Comment by UmairSyed** [comment]
hi guys 
have we found a more elegant solution as compared to the one involving kerberos?

**Comment by FireInWinter** [comment]
@Grey007 You can always switch to Java as the MS SQL JDBC driver supports NTLM authentication now.  I suggested it to both teams around the same time.  The Java team ran with it and the .net core team ignored it.  You might want to vote/comment on https://github.com/dotnet/SqlClient/issues/31 to maybe get someone to look at it again.

**Comment by capcom923** [comment]
> Hi @Grey007
> 
> Currently Integrated Security based Authentication with Native library is supported only on Windows, and the driver does not support NTLM Authentication.
> 
> We have no plans to support NTLM Authentication in SqlClient as it's insecure and deprecated now. Kerberos is more advanced and secure way of authentication, and always recommended.
> 
> There is also an option of [MSI Authentication](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) if your client machine is hosted in Azure Resource Manager, in which Managed Service Identity (MSI) access tokens can be generated and passed to the driver for creating connection without the need to pass credentials.

Hi @cheenamalhotra , thanks for your answer, but I want to know is that possible to use Kerberos auth in DB connection level like NTLM? Imagine that, our application requires 2 DB connections, the one is in domain A, the other is domain B.

**Comment by capcom923** [comment]
Thanks @David-Engel for your detailed explanation. But we still think Kerberos is a littlle bit complex.
As we known:
1. Java application can use JDBC(supports NTLM) to connect MS SQL Server by (domian/username, password).
2. .net application can use SqlClient to connect MySQL by (domian/username, password) when MySQL DB server installed PAM plugin which supports LDAP.

And I tested both above 2 approaches in our company. They work perfect.
So, what makes me confused is that why .net application **cannot** use SqlClient to connect MS SQL Server by (domian/username, password). It should be more easier since all are MS products, right?
If NTLM has security issue as @cheenamalhotra mentioned, can we check how JDBC works since it supports NTLM. Then implement it in SqlClient, can we?

Thanks,

**Comment by FireInWinter** [comment]
@capcom923 As far as I can see, they say it isn't secure, but allow SQL authentication, which is arguably much less secure than NTLM (See my comments in #31).  NTLM is available in the MS JDBC driver for SQL, so I guess they are trying to push SQL developers on Linux to Java instead of .net core?  Also, I would guess that 50%+ of database connections from Windows client use NTLM anyway due to a number of issues.  If NTLM is so insecure, then they should only support Kerberos connections.  Doesn't make sense to me, but I've given up on SQL at this point and have started to move on to MySQL.  The high costs, and disagreements like this, make it worth while to transition our company off of SQL Server.
