### ISSUE TITLE
Microsoft.Data.SqlClient's breaking change is forcing users to stay on 3.0.0

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/SqlClient#1449]
l am unable to update, because one the amount of work required, and two no one asked for this.

If you want to make a breaking change optional, then go ahead. To stop package updates because you expect end users to install a certificate, then either make SSL in SQL a checkbox, or I can't expect anyone will do this.

Also, people use my tools to build and test a connectionstring, but the actual deployment database might be an older version of SQL that doesn't have this requirement.

I wish you would make this a forward compatible update. I have already read articles discussing this.

Those who give up their liberty for security, will deserve and get neither.

**Comment by JRahnama** [comment]
@DataJuggler what makes it so difficult to add `Encrypt=false`to your connection string? That will bring the previous behavior back. SqlClient + native SNI is the only MS driver that had this security issue. All other drivers have been tested and confirmed.

**Comment by DataJuggler** [comment]
Because it breaks every connectionstring I have, including ones saved in databases and deployed on clients sites.

Leaving at 3.0.0 achieves the same effect, and no code changes, so why don’t you make your new feature optional? Same effect.

I won’t be installing a certificate into SQL Server ever, so if you want people to use the newest features, a core component like SqlClient should not be changed or you break backwards compatibility.

As I said, people will stop upgrading so I suggest you rethink this behavior.

**Comment by Wraith2** [comment]
> and two no one asked for this.

Someone somewhere asked or it wouldn't have been done. 
Now, if you want to question why it was asked for that seems reasonable and something you might get an answer to.

**Comment by Wayne-Mather** [comment]
Why cant you add code to see if the Encrypt flag already exists and if not add it on the fly? You could also inform all your clients about the version break and bump your tools version so they are aware. Nothing is broken if your clients stick to the old version and move across as they need to.

I agree that letting the users know of the change was the real issue here, but the workaround is very simple - once you get beyond the error message not making sense and blaming your own code 😊

**Comment by DataJuggler** [comment]
Let’s look at it from my point of view, and the point of view of everyone who is considering upgrading.

I have spent the last 7 weeks upgrading free code, haven’t earned a penny and I should be working, because .NET6 comes out. Only 1 year after I did this for .NET5.

I gain nothing by your changes for upgrading, and I must make dozens of changes, which leads to testing and hope nothing breaks, all for nothing to be gained.

Or, stay on Microsoft.Data.SqlClient 3.0.0, and no code changes are required and issue solved.

Which one do you think people are going to choose?

Why don’t you make the ones that want to make code changes opt in?

We trusted you not to break a core component, and you broke that trust. We just go to Manage Nuget Packages, see an upgrade, install it. App breaks.

Uninstall Update is going to be the workflow people choose.

I have a feature request to allow projects to set a Max Update available for components. If I release a Nuget package that references 3.0.0, and people see an update, and they update, my app breaks.

Not every company has 130,000 employees to update code.

**Comment by Wayne-Mather** [comment]
@DataJuggler - Just so you understand, I don't work for Microsoft. And I am upgrading an enterprise fullstack application to .NET 6 to stay on the LTS train. In fact, I have several enterprise application at different companies to upgrade - From internal Budget applications, to Farm Management to Auction Website. 

I understand your pain as I had the same problem doing my upgrade, but I found the solution to be fairly easy. So my comments was from someone who has to upgrade applications and the changes needed for some of those.

Yes my upgrade broke, yes I downgraded and had no problems. This meant it was not my code, so i started looking at what changed. This is standard software development practices as everything changes with time and you have to adapt to those changes or stay locked to a specific version of something because you cannot move forward. Personally, I think this change is rather minimal,  the fix simple, but the education around the change and problem was probably not transparent enough.

@JRahnama - Any reason the library cannot detect encrypt not set in the connection string and when a TLS error occurs, suppliment the message saying encrypt enabled by default, to opt out set encrypt = false in your connection string (or something like that)

**Comment by DataJuggler** [comment]
Do you get paid for it? If someone was paying me to make the changes, I love billable hours.

I am just expressing my opinion I think breaking a core component is wrong.

If you don’t, you are entitled to it. Breaking changes mean people may not upgrade is all I am saying, then updates are turned off essentially for those that think SqlClient was just fine the way it was. It connects to the database the way my code is.

Working code = happy users.

Let the community vote, and I vote to stay on 3.0.0 until you change it back.

**Comment by JRahnama** [comment]
@DataJuggler I am sorry that you had to go through changes in your code, but this is for benefit of every single user of the driver. I am not sure if we can talk on behalf of every user of the driver. So far the current version has been downloaded for almost 246k times. You can check it [here](https://www.nuget.org/packages/Microsoft.Data.SqlClient/) and the change has been accepted although it has caused some failures in other codes, but the change was adapted and codes were adjusted accordingly. Every single release of each product may come with breaking changes, you can compare net 6with other netcore versions, and that may block some users from upgrading for a while, but eventually codes are adjusted. It is not fair to force us to stop improving the driver because one user may not be able or does not want to change the code.

@Wayne-Mather we do not recommend setting `Encrypt=false` at production level unless the user knows its side effects. We encourage using certificates. The previous behavior had been wrong for years and we tried to avoid it for years, but we could not postpone it anymore. So, basically suggesting users to set the encrypt to false is against our goal of this change. The exception is thrown by the server since it is looking for a certificate and not been able to find it. If we just search the connection string for encrypt=false what happens to those with the certificate? It is server's responsibility to decide if a valid certificate is available or the handshake request should be rejected.

**Comment by DataJuggler** [comment]
Do you keep track of how many times it was uninstalled? That’s the only way to know if people stay on 4.

Or how many times the 3.0.0 version was downloaded by the same user that just downloaded the 4.0.0.

I’ve stated my opinion. I still think 8 Tracks were the best form of music, and if it weren’t for railroad tracks and hot cars it could still be true.

Why change what works.

**Comment by JRahnama** [comment]
I am closing this issue as there is nothing we can do to help with. Security is one of the most important features of cyber world and we are not apart from it. We wish there was a way to help and make the code transition process, but unfortunately there is not. Feel free to open a new issue if you have other concerns.
