### ISSUE TITLE
How to address EOL for runtime.win-x86.runtime.native.System.Data.SQLClient.sni

### ISSUE THREAD

**Issue by wherberg** [dotnet/SqlClient#1490]
Using System.Data.SQLClient(4.8.3), which in turn pulls in runtime.native.System.Data.SQLClient.sni(4.7.0), which includes runtime.win-x86.native.System.Data.SQLClient.sni(4.4.0) which Blackduck identifies as End of Life.  We don't use or need the x86 version so how do we remove or get rid of it without errors? 
![x86 Flex screen shot 3](https://user-images.githubusercontent.com/21268329/151428977-49d1dce3-432c-435a-b368-19570ec324fa.PNG)

**Comment by JRahnama** [comment]
@wherberg,

System.Data.SqlClient supports running on x86, x64, and arm64. In order to support that, SqlClient requires some native binaries that are platform-specific. Unfortunately, there's no way to tell the NuGet dependency chain that "this dependency is only required for this runtime target". If your application doesn't need to support running on x86, you are free to manually delete those dependencies from your output folder after building/publishing.

**Comment by JRahnama** [comment]
@wherberg is you question answered? If yes, please feel free to close the issue.

**Comment by AraHaan** [comment]
@JRahnama there is a way to do that, have in the nuget package to SqlClient to:
- Add build/<package name>.props
  - add the native nuget package depending on the value of ``$(RuntimeIdentifier)``.

Then on restore on the user the nuget package would add the reference to the native dependency that they need to their project for the.
