### ISSUE TITLE
Please take the SqlClient GitHub survey

### ISSUE THREAD

**Issue by David-Engel** [dotnet/SqlClient#1504]
We're surveying you, the members of the community in this repo, to learn how we were doing as maintainers. Whether you've been involved for years or you're relatively new please tell us about your experience participating and contributing to the project. The survey covers many dotnet repos, so be sure to answer for dotnet/sqlclient. It should only take a few minutes:

[https://www.surveymonkey.com/r/8QTQTGJ?Source=sqlclient](https://www.surveymonkey.com/r/8QTQTGJ?Source=sqlclient)

Thanks!

**Comment by danmoseley** [comment]
@Wraith2 we ended up updating the original survey. If you already did that survey, it might not let you do it again. But the survey is repeated up to 3 times so that people can answer for up to 3 repos. It's possible you might be able to jump to 3rd one if you replace the code above with 8TWNFZL?Source=sqlclient

**Comment by Wraith2** [comment]
The second code worked, thanks :)

**Comment by danmoseley** [comment]
@David-Engel could you please close and un-pin this as the survey closed. Thanks to the 13 folks who responded for this repo.

**Comment by JRahnama** [comment]
Closing the issue as the survey as it is closed.
