### ISSUE TITLE
How to use System.Data.IDbConnection & IDbTransaction with Microsoft.Data.SqlClient?

### ISSUE THREAD

**Issue by tobymartyn** [dotnet/SqlClient#1516]
My organisation supports multiple different DB providers, and as such handles lower level connection details using [System.Data.IDbConnection](https://docs.microsoft.com/en-us/dotnet/api/system.data.idbconnection) and [System.Data.IDbTransaction](https://docs.microsoft.com/en-us/dotnet/api/system.data.IDbTransaction).
Microsoft.Data.SqlClient does not play nicely with objects implementing these interfaces (e.g. type conversion issues from system.data.sqlclient) and there does not appear to be a way to perform explicit conversions between types.

What is the suggested approach for integrating Microsoft.Data.SqlClient with IDbConnection and IDbTransaction?
I have checked the FAQ and porting cheat sheet.

**Comment by roji** [comment]
@tobymartyn what exact issues are you running into, can you post some code and errors?

BTW it's highly recommended to use the abstract class DbConnection and DbTransaction, rather than the interfaces. The interfaces were introduced very early and could not be evolved (since doing so would break existing implementations), so they lack APIs which were introduced later (for example, the interfaces have no async methods). The abstract base classes provide the same abstraction but with the newer APIs.

**Comment by tobymartyn** [comment]
Thanks @roji. I've been able to convert a subset of the system to use the DbConnection and DbTransaction classes. Unfortunately, the system I'm working with deals with the IDb interfaces at a very low level and needs to ensure backward compatibility with prior versions and other non-MS database providers, so simply switching out for the updated types is not a straightforward process. 

Thanks for confirming what the preferred way forward is - I can take that into any future refactoring of this infrastructure that we do.

Regards,
-T.
