### ISSUE TITLE
SQL Server pre-login handshake failed Android .NET 6 or .NET 7

### ISSUE THREAD

**Issue by keventheriault** [dotnet/SqlClient#1840]
I use new stack Android .NET 6 or .NET 7 in C# (notXamarin, the new Stack). I have SQL Server 2019 and Visual Studio 2022.
During the connection to server with ADO.NET (Microsoft.Data.SQLClient) I have this error : 

A connection was succesfully established with the server, but then an orror occured during the pre-login handshake TCP provider error 35

Thanks !!!

**Comment by lcheunglci** [comment]
This seems like a duplicate of #1662 and temporary workaround has been suggested in that thread.

**Comment by frsimard** [comment]
Same here ! We tried in iOS (.NET 6) and it worked fine but on Android (.NET 6), it does not.

**Comment by maxz0ne** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/22328851/202309663-9c11604b-4d07-4c3c-a938-ee279b3b8116.png">
We are stuck on the same problem. (Android with DOTNET6)

**Comment by lcheunglci** [comment]
I have a few questions to get a better context of how you're connecting.  

1. What is your connection string?
2. What version of Microsoft.Data.SqlClient are you using?
3. Does your Sql Server have "force encryption" enabled?
4. Does your Sql Server reference a certificate? If so, is a self-signed certificate or is it one that is provided from a Trusted CA?
5. Have you tried Encrypt=false or TrustServerCertificate=true in your connection string?

**Comment by keventheriault** [comment]
1.connexion = new SqlConnection(@"Server=xxx.xxx.xxx.xxx;Database=xxx; User Id=xxx;Password=xxxxxxxx");
2. Microsoft.Data.SqlClient 5.0.1
3. No
4. No
5. Yes, not resolve the problem

Thanks !!!

**Comment by lcheunglci** [comment]
Thanks for the details @keventheriault .  It seems like it is similar to the issue #1662, and currently it's under investigation and the workaround at the moment is to generate and add a self-signed certificate to the server and install it on the device, and the steps can be found [here](https://github.com/dotnet/SqlClient/issues/1662#issuecomment-1252699051) and [here](https://github.com/dotnet/SqlClient/issues/1662#issuecomment-1260858334).

**Comment by mharry32** [comment]
I find an unorthodox solution , and it works.
1. clone the Micosoft.Data.SqlClient( I cloned the main branch , at that time the Microsoft team are developing the 5.x version of this library)
2. Open the solution "Microsoft.Data.SqlClient.sln" in vs , and locate to the project "Microsoft.Data.SqlClient" under the "netcore" directory
3. Locate to "SendPreLoginHandshake" method in TdsParser.cs (near lines 705) , and add this line:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/8725661/203820548-0bbc28c9-ebe8-40ea-872d-fbcc10155f5e.png">
This line of code will set encrypt option flag to "NOT_SUP" , then later this method will inform the server do not try to encrypt the data using ssl , so it prevent the real cause of the error : The remote certificate validation callback doesn't work correctly on Android and it is tracked in [](https://github.com/dotnet/runtime/issues/45741)
4. After you modified the source code of the library , you can pack the library ( simply set the configuration to "release" and right click the project -> "Pack Microsoft.Data.SqlClient" , and then you can find the nuget package in the "artifacts" directory . you can add it to your project , it will override the original library referencing by EFCore , or something else..

WARNING: If you chose this solution , it may reduce security , because the network communications between server and client is not protected by ssl.

**Comment by lcheunglci** [comment]
Thanks @mharry32 for sharing the details. In summary, from what I understand from the dotnet runtime thread is that it looks like there was a change in the dotnet runtime that prevented backward compatibility for older versions of Android (i.e. below 22) with using the ssl certificate resulting this workaround by hardcoding encryption support to be disabled for all platforms from the driver. which is a security risk (since credentials are always encrypted, but this will disable it) which you already mentioned.

**Comment by lcheunglci** [comment]
Also, it looks like there's PR opened https://github.com/dotnet/runtime/pull/77386 to address the self-signed certificate issue on Android, so I'm going to mark this as external.

**Comment by cheenamalhotra** [comment]
Closing as stale and external.
