### ISSUE TITLE
clarify the connection string usage for a sql server with a named instance

### ISSUE THREAD

**Issue by bleissem** [dotnet/SqlClient#1932]
Hello,

I want to use ef core 6 ( along with .Net 6 ) to connect to a sql server instance with a named instance e.g. server\myinstance .
The documentation under
https://learn.microsoft.com/de-de/ef/core/miscellaneous/connection-strings
shows how to connect to a local db.
When I want to use connection string in the appsettings.json file:

"Persist Security Info=True;Server=server\\myinstance;Database=mydatabase;user id=sql_user;password=password;trusted_connection=true;MultipleActiveResultSets=True;App=EntityFramework"

I'm getting an error 
Microsoft.Data.SqlClient.SqlException: 'Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=21139; handshake=32; '

When I use SQL Server Management Studio with version v18.12.1 the connection to the database basically works.
I would like to know what the correct connection string for a database with a named instance ( not default instance ) would look like.
Thanks in advance.

Regards
Alex B.

**Comment by roji** [comment]
Transferring to sqlclient as this isn't related to EF.

**Comment by ErikEJ** [comment]
Please share a repro

**Comment by blaekhoermann** [comment]
By adding "Connect Timeout=30" connection timeout does not expire but it takes a long time for connect. 

Why does take a connection creation with named instance so much longer as with a default instance on sql server 2022 (platform: windows)?

**Comment by JRahnama** [comment]
@blaekhoermann to answer your question
There are to two kinds of instances:

1. Automatic instances: They are public and are creeated and managed automatically for the user and can be used by any application. One automatic instance of LocalDB exists for every version of LocalDB installed on the user's computer.
2. Named instances: they are private and are owned by a single application that is responsible for creating and managing the instance.

Now, connection string for public localdb should look like `Server=(localdb)\MSSQLLocalDB;Integrated Security=true`

In order to create and connect to a named instance you need to create one by running:
``` powershell
SqlLocalDB.exe create "<desired instance name>"
SqlLocalDB.exe share "< provided name in previous step" "<give` it a name to for the shared instance>"
SqlLocalDB.exe start "provided name in step one."
SqlLocalDB.exe info "provided name in step one."
 
sqlcmd -S <the value you got for Instance name from the info command> (np:\\.\pipe\LOCALDB#<use your pipe name>\tsql\query)
CREATE LOGIN <give it a username> WITH PASSWORD = ''provide a password';
GO
CREATE USER NewLogin;
GO
EXIT
```

Info command will print something similar to the below picture:


![image](https://user-images.githubusercontent.com/32077152/220977791-d2b1a1ea-9cb5-4221-8472-751d794c9b16.png)

now you can always use the value of Instance pipe name provided from running command number 4, but the number inside the value may change if you restart or stop the named instance.

A regular connection string could be like : 
`Server =(localdb)\.` this will connect to default automatic instance (MSSQLLocalDB)
`Server =(localdb)\.\<named instance>`

Have you tested with Visual Studio to see if `SQL Server Object Explorer` is able to find your named instance?

**Comment by ErikEJ** [comment]
@JRahnama There is also normal named instances??

**Comment by JRahnama** [comment]
@ErikEJ it is either automatic instance which is `MSSQLLocalDB` or is a named instance. each one of these could be shared according the [documentation](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver16#automatic-and-named-instances). What do you mean by normal for `(localdb)`

**Comment by ErikEJ** [comment]
I do not see any reference to localdb in the original post...

**Comment by JRahnama** [comment]
> I do not see any reference to localdb in the original post...

My assumption was based on the provided link and keyword `local db` from the original post... maybe I got it wrong?

**Comment by JRahnama** [comment]
@blaekhoermann, sorry if the previous answer was a bit confusing, for general or as @ErikEJ mentioned normal named instances you will need:

`<your Server Name>\<Instance name>,port`

For example, if your server or local machine's FQDN is teset123 and your default instance name is MSSQLSERVER with default port of 1433:

it would be: `test123\MSSQLSERVER,1433`. Port has to be specified as this is the default value otherwise connection fails. If your are going to use a different name, you need to setup an alias for that. If you have created an alias then you do not need to specify the port number.

Hope I was able to answer your question.

**Comment by JRahnama** [comment]
Closing the issue due to inactivity. Feel free to comment or open a new issue.
