### ISSUE TITLE
The certificate chain was issued by an authority that is not trusted

### ISSUE THREAD

**Issue by rajibsm** [dotnet/SqlClient#1993]
**Background**
Our database is hosted on Amazon RDS which provides SSL server certificates whose root CA is not in the Trusted Root Certification Authorities in the OS by default.  This creates an issue when attempting to negotiate client side encryption when connecting to SQL Server. 

Based on [this ](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/SQLServer.Concepts.General.SSL.Using.html)AWS article, I understood that if encryption is forced at the server level, then client certificate negotiation is not required. This has been the current approach for our Database and has been working for years using System.Sql.Client.  Even though encryption is not specified in the client connection string, all connections are encrypted. This is verifiable using a query on SQL server which shows us that all connections are encrypted. 

**Current issue**
While upgrading our application from Net Core 3.1 to Net 6.0, we updated our code to use Microsoft.Data.SQLClient instead of using System.Data.SqlClient. I understand that there is a breaking change in Microsoft.Data.SQLClient that sets the Encrypt property in the SQL connection string to true by default. Since we force encryption at the server as stated in the previous paragraph, we set Encrypt to false in the connection string. However, we are running into the error below. 

 "Microsoft.Data.SqlClient.SqlException: 'A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)'"

Adding the AWS certificates to the Trusted Root Certification Authorities for all users is not trivial, will be difficult to maintain, requires admin access on client computers to install, and is therefore an undesirable path forward.

Setting TrustServerCertificate=True works but we do not want to do this as this leaves the server in an insecure state.

During our research into the issue, we found a new connection string property in Microsoft.Data.SQLClient called ServerCertificate at this [link](https://learn.microsoft.com/en-us/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver16). 
We tried to use this property by downloading the certificate from Amazon, and setting the value of ServerCertificate to the path of the amazon certificate on local directory. It did not work and yielded the following error message: 
Microsoft.Data.SqlClient.SqlException: 'A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate is not valid for the requested usage.)'

At this point, we are reaching out to the community to see if anyone has any ideas on how to connect to SQL Server using Microsoft.Data.SQLClient using encryption, but without having to install certificates on the client machine.  

Using ServerCertificate property seemed like a good workaround, but we were not able to get this working for us.

**Comment by JRahnama** [comment]
@rajibsm thanks for the detailed explanation. What platform is your application running on (Windows, Linux, ...)?

**Comment by rajibsm** [comment]
@JRahnama The application is running on Windows.

**Comment by HamsterExAstris** [comment]
> Adding the AWS certificates to the Trusted Root Certification Authorities for all users is not trivial, will be difficult to maintain, requires admin access on client computers to install, and is therefore an undesirable path forward.

Installing the root certificates in the current user's Trusted Root Certification Authorities store on Windows does not require admin access. (This is the route we're going for our end users' laptops; we're only installing in the machine store on servers, where we have admin access already.)

> Setting TrustServerCertificate=True works but we do not want to do this as this leaves the server in an insecure state.

It's the same state you were in before the upgrade.

**Comment by cheenamalhotra** [comment]
@rajibsm 

What you're referring to was added to MDS in v2.0 as a breaking change, so this is by-design:
https://learn.microsoft.com/en-us/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver16#breaking-changes-in-20

_"The driver will now perform Server Certificate validation when the target SQL Server enforces TLS encryption, which is the default for Azure connections."_

**Comment by David-Engel** [comment]
> > Setting TrustServerCertificate=True works but we do not want to do this as this leaves the server in an insecure state.
> 
> I'm not sure I understand server implications, maybe could you elaborate? As trusting server certificate is a client side setting, as it was done by default with forced server encryption until this change.

There seems to be confusion here on the behavior of SqlClient before the changes in MDS 2.0.

In all versions of System.Data.SqlClient and MDS versions before 2.0, when Encrypt=false (the default), server certificates were never validated by the client, regardless of the TrustServerCertificate setting. (Validation ensures the certificate chain is trusted and valid and that the server name being connected to matches the name in the certificate.) When encryption is enforced from the server side, yes, encryption is negotiated but the client never validates the server certificate. While this should protect the connection from simple observers, it does not prevent MITM attacks where a middle man may present the client with its own certificate (or even tell the client it doesn't need to encrypt) and proxy the encrypted connection to the server. As HamsterExAstris said, "[Setting TrustServerCertificate=True is] the same state you were in before the upgrade."

The above is why we've been adjusting default behavior, breaking backwards compatibility. Most people aren't security experts and don't understand the security implications of maintaining the status quo. In order to truly secure your environment, you must enforce encryption from the client side and used validated server certificates (either via a public trust chain or a private, manual one).
