### ISSUE TITLE
Microsoft.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by Benknightdark** [dotnet/SqlClient#2030]
## Issue Description
I have an ASP.NET Core MVC project targeting .NET 7 and a library project also targeting .NET 7. After referencing the library project in the MVC project and publishing it, I receive the following error when trying to use the `DbContext`:

`System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.`

## Expected Behavior
I expected to be able to use the `DbContext` without any issues after referencing the .NET 7 library project.

## Steps to Reproduce
1. Create a new ASP.NET Core MVC project targeting .NET 7.
2. Create a new class library project targeting .NET 7.
3. Add a database context to the class library project using Microsoft.EntityFrameworkCore.SqlServer package.
4. Add a reference to the class library project in the MVC project.
5. Publish the MVC project and attempt to use the database context.

## Additional Information
- I have tried the solutions suggested in [Microsoft's documentation](https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-supported-platforms).
- I have also tried downgrading the class library project to target .NET 6 and that resolved the issue. However, I need to target .NET 7 for other reasons.
- This is a severe issue as it prevents me from using a library project that targets .NET 7 and Microsoft.Data.SqlClient.
- This issue did not occur when using .NET 6 in both projects.

**Comment by JesperLundberg** [comment]
You'd need to find the runtime id for the windows you're using.

I found the Linux one somewhere in Microsofts documentation. Sorry that I can't be more specific.

Following the same logic as the Linux one it'd be `Windows-x64` but I'm just guessing here.

**Comment by SudoCerb** [comment]
Microsoft's documentation that is linked by OP leads to a 404.

Great.

I have a similar issue. Creating it now and linking to this.

I'm on Windows 11.

**Comment by JRahnama** [comment]
Could any one here provide a simple repro of the issue?

**Comment by SudoCerb** [comment]
> Could any one here provide a simple repro of the issue?

I'll happily do so - just need to create one. Will take a crack at this first thing in the morning.

**Comment by SudoCerb** [comment]
Hi @JRahnama , I've created the simplest case I could - 

https://github.com/SudoCerb/manictime-microsoft.data.sqlclient-min-repro

Instructions are in the README.md.

I hope that this helps!

**Comment by Kaur-Parminder** [comment]
I tried .Net7 ASP.NetCore WebAPP with class library targetting .NET7 on Windows 10. I am not seeing the exception, I am attaching the sample. 

The steps I followed:

Create Database using script https://github.com/dotnet/SqlClient/blob/main/tools/testsql/createNorthwindDb.sql
Create Class Library .Net7. and reference following packages
` <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
`
Run command below to create DBContext for Northwind DB created above

`Scaffold-DbContext "Server=localhost;Database=Northwind;Integrated Security=true;Encrypt=false;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models`

Created WebApp (MVC) targetting .Net7
Reference the class library to Web App project.
Added code to Controller to get data from DB.
`            var context = new NorthwindContext();
            var test = context.Employees.First();`



[Sample.zip](https://github.com/dotnet/SqlClient/files/11445672/Sample.zip)

**Comment by JesperLundberg** [comment]
Just to add to what I wrote earlier. The link where I found the RID for Linux is [here](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog).

**Comment by SimonGeering** [comment]
Just wanted to add that I'm getting the same exception when init dbcontext, .net 7 (latest sdk) on Linux mint 21 running in blazer server with a DAL in a separate DLL project. 

Running the blazer solution on the metal and connecting to a SQL 2022 instance in a container. 

Exactly the same code works fine on two separate windows 10 enterprise boxes, connecting native and container SQL server 2022 respectively.

Repo is opensource here, and reproducible from the PlatformNotSupportedException branch [https://github.com/SimonGeering/AdminAssistant/tree/PlatformNotSupportedException](https://github.com/SimonGeering/AdminAssistant/tree/PlatformNotSupportedException)

I'll try to get the time this week to add repo instructions but give it the config for the SQL server and run an ef migration and boom.

Happy to help with testing if any fix can come for this, will also try it with the 8 preview when I get the chance and let you know.

**Comment by DavoudEshtehari** [comment]
Detecting the correct target framework is on runtime to be discovered not MDS. Any failed attempts will fall back to the "not supported platform" dll and throw this exception which is by design.

**Comment by SudoCerb** [comment]
> Detecting the correct target framework is on runtime to be discovered not MDS. Any failed attempts will fall back to the "not supported platform" dll and throw this exception which is by design.

I think it would be quite useful for the error to say something like that. I have no idea how to get around this but that error message would have been more helpful!

**Comment by derek-mba** [comment]
In my case, I was compiling just fine yesterday; moved to a new account on the same server (also Linux Mint 21) today and even though I'm targetting dotnet6 and have only dotnet 6 runtimes and SDK installed, I'm getting the same.

**Comment by derek-mba** [comment]
On Mint/Ubuntu it seems to be an issue with the Ubuntu versions of Dotnet. I replaced them with the Microsoft packages from  https://packages.microsoft.com/ubuntu/22.04/prod and all is now fine. [Instructions at https://learn.microsoft.com/en-ca/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository]

**Comment by DanwithArduino** [comment]
I'm having this issue as well now. All packages and dotnet SDK on my 20.04 server are up to date. Builds fine locally, but fails on server deploy. Dotnet 7.

**Comment by dungarDot** [comment]
For what it's worth I just started having failures on this with a repo that worked two weeks ago. I had to re clone down the repo, made some code changes, and now it doesn't work.  Windows 10, net7.0.  Setting self contained to false has not helped.

**Comment by DavoudEshtehari** [comment]
Closing it as it's external. Feel free to post in this thread.

**Comment by joaopf-silva** [comment]
Did someone manage to get this working for Windows?

Windows 11, Visual Studio 2022, .NET Standard 2.0 Class Library project

**Comment by dragos-durlut** [comment]
For Docker DOTNET Alpine I had to set the runtime id to `linux-musl-x64`

Previously I had only the architecture set to `amd64`.

```yml
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

RUN dotnet publish -r linux-musl-x64 "path.to.csproj" -c Release -o /app \
    --self-contained true \
    /p:PublishSingleFile=false
    
FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine AS final

ENTRYPOINT ["./entry-point-file"]
```

**Comment by RobDaytona** [comment]
I just don't understand how any one is supposed to develop using Microsoft .net technologies any more. The stuff is so buggy it drives me insane. Yesterday my API was working perfectly accessing stored procs no problems, to day first thing it says is: [Microsoft.Data.SqlClient is not supported on this platform](https://github.com/dotnet/SqlClient/issues/2030#top)
#2030 and the only thing that has changed is I implemented bearer token security into the api call? so no mods whatsover with sql sever.. or anything database related and I am getting "Microsoft.Data.SqlClient is not supported on this platform" - wtf I have an app to write and I am constantly running into issues all the time. does my head in. I have basic bugs open in .net Maui, that get verified as bugs, and previously xamarin, I report the bug, the bug gets verified, then never fixed.. this is ridiculous. Does any one have any ideas what is causing this issue? and or recommendations on what to fix, this thread is very confusing with people on about linux etc.. my situation is .net8, .net aspcore api project (or whatever its called these days).. running on a dedicated API dns on a windows 2016 server.. so where is the issue is it the api project ? or is it the server, and why did this work yesterday and todak after implementing token bearer security on the api call it does this? its madness.. aaaaargg!!!

**Comment by RobDaytona** [comment]
Update: I reverted to yesterdays backup of the API and Client, deployed the API to the win 2016 server and it successfully calls the database strored procs with out this stupid error. As I said the only thing I did was add Token Bearer API security to the API and Client and this error suddenly popped up.. I am going to try repeat these steps and see if it does it again. I hope not!

**Comment by IzharAzati** [comment]
In my case, adding to .csproj file:

    
    **<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>**
    
    
    **<RuntimeIdentifier>win-x64</RuntimeIdentifier>**

managed to make it work.
(SQL, ODBC, ...)
In my case, I'm developing a DLL plugin for the AutoCAD software, the problem is that all Microsoft's tests / examples are for EXE applications and not for DLLs.

**Comment by johnricketts** [comment]
I also had this problem when upgrading from .NET 7.0 to .NET 8.0. Adding the nuget package
`<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />`
To the executing application csproj fixed it. Why I don't know.

**Comment by shonuff373** [comment]
> I also had this problem when upgrading from .NET 7.0 to .NET 8.0. Adding the nuget package `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />` To the executing application csproj fixed it. Why I don't know.

I'm running into the same issue for the same reason. I read on a few other forums that downgrading to 5.1.5 helped. But that hasn't worked for me.

**Comment by bh3605** [comment]
.net 8 here. Still doesn't work.

**Comment by Woudjee** [comment]
**I HAVE A SOLUTION FOR WINDOWS PEOPLE:**

This guy is right:

> I also had this problem when upgrading from .NET 7.0 to .NET 8.0. Adding the nuget package `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />` To the executing application csproj fixed it. Why I don't know.

Why? I'm not sure, but I believe that it has something to do with our sql projects being class libs instead of applications, thereby messing up package references. I have had similar problems with different packages some times. It has something to do with how the project is build for production being different than the project being build for debugging purposes. When debugging, all dll's are copied to the right place, when creating a release, they don't. This is something that is supposed to be fixed on the Microsoft side, like @RobDaytona was complaning about. I can relate to what you're writing very well man.

So to solve these and similar issues: make sure that you reference the missing dll in your calling project, and most likely you're good to go. (I used the latest version).

**Comment by mavToday** [comment]
The Package Microsoft.Data.SqlClient has a Reference to Microsoft.Data.SqlClient.SNI.runtime. This Packages includes a native assembly, that is necessary for the SqlClient with net8.0.

However, if this native assembly is not present relative to the application (e.g. runtimes\win-x64\native), it will result in the "Microsoft.Data.SqlClient is not supported on this platform" exception.

We put our NuGet-Packages not next to our application, but in a separate folder with our own AssemblyLoadContext. We can load the Microsoft.Data.SqlClient.dll Assembly, and even the native Microsoft.Data.SqlClient.SNI.dll via AssemblyLoadContext.LoadUnmanagedDll, but still resulting in the error. If we move them to the outputfolder for the application (oder unit-test), it works. The crazy thing is, that i can access the imported functions and call them correctly like in SniNativeMethods.cs 

For me it looks like, the resolving for the native assembly is buggy. But i dont find any related code in the repository.

**Comment by NavirBox** [comment]
No way this is closed. It's still happening with 9.0

**Comment by NintendoPlayer** [comment]
Hi!  Same problem here.  It's driving me crazy, I don't know how to solve this issue.  Everything was working in my project, had to update System.Data.Sqlclient because it was deprecated and the this nonesense started.  Now going back to System. Data.Sqlclient and it shows me the same message.

In my case I have a main project for my app and then several projects that compile as libraries.  Almost all projects reference the nuget.  Then I have a visual studio setup project that generates the installer.  Everything works properly, installs the app but throws the error.  I don't really don't know what I have to do in my solution to really solve the issue.

**Comment by IzharAzati** [comment]
Try to revert to the oldest version of **System.Diagnostics**
I had a similar problem when I built a DLL as an ADDIN for a graphics program (AutoCAD).
Another way, if you have a project/projects with **Multi Target**, create projects for each **Target**.

**Comment by prlcutting** [comment]
I'm running into this problem too. We have a library project whose assembly is resolved dynamically at runtime (like a plugin) into the main application, and it's this library that has a dependency on `Microsoft.Data.SqlClient`. I have confirmed that `Microsoft.Data.SqlClient.dll` is copied to the correct location for the hosting .NET application, and that the native `runtimes/win-x64/native/Microsoft.Data.SqlClient.SNI.dll` dependency exists too. But no amount of cajoling will get this thing to work without throwing a `PlatformNotSupportedException`. The only recourse is adding an artificial and unwanted dependency from the main application's project to `Microsoft.Data.SqlClient`. But _why_? Why does this work? What is this actually fixing? Why can't `Microsoft.Data.SqlClient` resolve its native dependencies like our other NuGet packages that have native dependencies? Those work fine, without a hack to add them to the main application as a direct dependency.

Since this issue is closed (despite continuing community feedback about recurring problems), will these comments even be observed by anybody at Microsoft who can perhaps look into it?

**Comment by AaronAmberman** [comment]
I have just now run into this problem too. I wanted to add my insight from my investigations in case they help point the community in the right direction.

Generally, in NuGet packages, the DLL in question we seek is located in the lib directory in a target framework moniker (TFM) sub-directory (.net6.0, .net7.0-windows, .net8.0-windows10.0.26100, etc.) inside your package. I think this is not true for this particular Microsoft.Data.SqlClient NuGet package. The package is found in the runtimes sub-directory, more specifically runtimes/win/lib/TFM (in my case runtimes/win/lib/net8.0).

If you were to install this package into a project via nuget.exe then you will see several copies of the Microsoft.Data.SqlClient.dll inside the downloaded resource. 1 in the aforementioned lib sub-directory (Microsoft.Data.SqlClient.6.1.4/lib/net8.0/Microsoft.Data.SqliClient.dll) which is not the one you want but is typically the one that NuGet finds if you are not a windows executable. If you were to open this one in any decompilation program (like dotPeek) you will see every declaration in every type simply throws a PlatformNotSupportException. They don't look at anything or inspect any parameters. 100% of everything just blindly throws a PNSE. This DLL in .NET8 is a little over 900KB.

Now the other DLL, in runtimes, is the one we want. This is the one that contains the goods (has the actual code and doesn't just throw PNSEs everywhere). So this DLL, (Microsoft.Data.SqlClient.6.1.4/runtimes/win/lib/net8.0/Microsoft.Data.SqliClient.dll), is the one that is typically found when we reference this NuGet package in a WinExe application. I think that is because of the EXE versus LIBRARY project types in terms of how NuGet.exe (and the newer dotnet variants) does resource lookup. This DLL in .NET8 is about 2.1MB. Big difference from the one that just throws a bunch of exceptions.

So if you reference this NuGet package in a DLL project it might never work right if MS doesn't change how the package is put together or how resource look ups work for DLL type projects within NuGet. 

I am not a guru and I definitely don't understand this stuff at a low level. Just trying to add some insight as to why a lot us seem to be seeing this PlatformNotSupportException. Hope this helps someone out there. :)

**Comment by Woudjee** [comment]
> I have just now run into this problem too. I wanted to add my insight from my investigations in case they help point the community in the right direction.
> 
> Generally, in NuGet packages, the DLL in question we seek is located in the lib directory in a target framework moniker (TFM) sub-directory (.net6.0, .net7.0-windows, .net8.0-windows10.0.26100, etc.) inside your package. I think this is not true for this particular Microsoft.Data.SqlClient NuGet package. The package is found in the runtimes sub-directory, more specifically runtimes/win/lib/TFM (in my case runtimes/win/lib/net8.0).
> 
> If you were to install this package into a project via nuget.exe then you will see several copies of the Microsoft.Data.SqlClient.dll inside the downloaded resource. 1 in the aforementioned lib sub-directory (Microsoft.Data.SqlClient.6.1.4/lib/net8.0/Microsoft.Data.SqliClient.dll) which is not the one you want but is typically the one that NuGet finds if you are not a windows executable. If you were to open this one in any decompilation program (like dotPeek) you will see every declaration in every type simply throws a PlatformNotSupportException. They don't look at anything or inspect any parameters. 100% of everything just blindly throws a PNSE. This DLL in .NET8 is a little over 900KB.
> 
> Now the other DLL, in runtimes, is the one we want. This is the one that contains the goods (has the actual code and doesn't just throw PNSEs everywhere). So this DLL, (Microsoft.Data.SqlClient.6.1.4/runtimes/win/lib/net8.0/Microsoft.Data.SqliClient.dll), is the one that is typically found when we reference this NuGet package in a WinExe application. I think that is because of the EXE versus LIBRARY project types in terms of how NuGet.exe (and the newer dotnet variants) does resource lookup. This DLL in .NET8 is about 2.1MB. Big difference from the one that just throws a bunch of exceptions.
> 
> So if you reference this NuGet package in a DLL project it might never work right if MS doesn't change how the package is put together or how resource look ups work for DLL type projects within NuGet.
> 
> I am not a guru and I definitely don't understand this stuff at a low level. Just trying to add some insight as to why a lot us seem to be seeing this PlatformNotSupportException. Hope this helps someone out there. :)

Well done researching this. Your conclusions seem very reasonable. It’s the perfect substantiation for the message I posted here a while back. 👍 I’m happy I understand this slightly better now.

**Comment by bootrider** [comment]
It is still happening in the version 7.0.1.

**Comment by bootrider** [comment]
this solve my issue:
Making the upgrade from .NET8 to .NET10 I had:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>CA1416</NoWarn>
    <Platforms>x64</Platforms>
  </PropertyGroup>
...
```

I changed to:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>     <!-- here is the detail -->
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>CA1416</NoWarn>
    <Platforms>x64</Platforms>
  </PropertyGroup>
...
```
