### ISSUE TITLE
Multiple Kerberos Principals

### ISSUE THREAD

**Issue by ramkumarchan** [dotnet/SqlClient#2085]
We have a dotnet core application (centos, .NET core 6, k8s) that connects to SQL Server using Kerberos (underlying Microsoft Active Directory Domain Controller). Using Microsoft.Data.SqlClient nuget package 5.1.0. For auth, we specify [SqlAuthenticationMethod.ActiveDirectoryIntegrated](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlauthenticationmethod?view=sqlclient-dotnet-standard-5.1) value in [SqlConnectionStringBuilder.Authentication](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.authentication?view=sqlclient-dotnet-standard-5.1#microsoft-data-sqlclient-sqlconnectionstringbuilder-authentication) Property

We are currently using a kerberos sidecar for ticket management for a single principal. We are able to connect to SQL using this single principal. Now we would like to use multiple principals to connect to multiple SQL DB's from a single dotnet core application. How can we achieve this using nuget package Microsoft.Data.SqlClient. It seems possible in JDBC using property name "jaasConfigurationName" : https://github.com/Microsoft/mssql-jdbc/issues/828.

**Comment by David-Engel** [comment]
I'm not sure if it's possible. You'd need to be manually controlling the default principal, which is what the underlying .NET libraries use. Since you say you have Kerberos working with Authentication=ActiveDirectoryIntegrated, maybe you can simply set up multiple tickets and specify `Authentication=ActiveDirectoryIntegrated` and `UserID=<user@DOMAIN>`. That assumes the driver is not going down the IntegratedSecurity path, but is going down the AzureAD path for ActiveDirectoryIntegrated, where UserId is used as a hint for the MSAL library.

If that doesn't work, you can try looking into [WindowsIdentity.RunImpersonated](https://learn.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=net-7.0), but I'm not sure if that works outside of Windows.

MDS doesn't have an equivalent to the jaasConfigurationName setting in the JDBC driver.
