### ISSUE TITLE
Microsoft.SqlServer.Types SqlGeography.Parse - ThowIfGLNativeLibraryNotLoaded

### ISSUE THREAD

**Issue by Ansssss** [dotnet/SqlClient#2148]
### Describe the bug
Using the latest Microsoft.SqlServer.Types [nuget ](https://www.nuget.org/packages/Microsoft.SqlServer.Types) in a C# application (dotnetfiddle repro [here](https://dotnetfiddle.net/MFRWCN)), the SqlGeography.Parse method fails for a polygon when run on a Linux system.

```
Unhandled exception. System.PlatformNotSupportedException: Required functionality is not implemented on this platform (Linux 5.15.0-1042-azure #49-Ubuntu SMP Tue Jul 11 17:28:46 UTC 2023 - X64).
   at Microsoft.SqlServer.Types.GLNativeMethods.ThowIfGLNativeLibraryNotLoaded()
   at Microsoft.SqlServer.Types.GLNativeMethods.GeodeticIsValid(GeoData& g, Double eccentricity, Boolean forceKatmai)
   at Microsoft.SqlServer.Types.SqlGeography.IsValidExpensive(Boolean forceKatmai)
   at Microsoft.SqlServer.Types.SqlGeography..ctor(GeoData g, Int32 srid)
   at Microsoft.SqlServer.Types.SqlGeography.GeographyFromText(OpenGisType type, SqlChars taggedText, Int32 srid)
   at Microsoft.SqlServer.Types.SqlGeography.Parse(SqlString s)
   at Program.Main()
Command terminated by signal 6
```

### To reproduce

Use the following C# code and add the Microsoft.SqlServer.Types nuget version 160.1000.6 to the solution.

```c#
public class Program
{
	public static void Main()
	{
		Microsoft.SqlServer.Types.SqlGeography.Parse("POLYGON((-71.00318 24.99757, -70.99155 25.00037, -70.99785 25.00931, -71.00318 24.99757))");
	}
}
```

### Expected behavior
The parse to succeed.

**Comment by Ansssss** [comment]
I tested the same code using the dotMorten.Microsoft.SqlServer.Types nuget (version 2.5.0), and it succeeds.
https://dotnetfiddle.net/n6A6Fg

**Comment by JRahnama** [comment]
@Ansssss thank you for reporting this. We will look into this issue and will get back to you soon.

**Comment by BartjeD** [comment]
We also have this issue.

We installed the latest Microsoft.SqlServer.Types. Local testing worked but release builds fail with this error.

**Comment by Ansssss** [comment]
@BartjeD Are you saying that your tests fail on Windows in release builds? Because I am seeing it succeed on Windows when testing and fail on Linux.

**Comment by BartjeD** [comment]
> @BartjeD Are you saying that your tests fail on Windows in release builds? Because I am seeing it succeed on Windows when testing and fail on Linux.

We diagnosed that the NuGet for `Microsoft.SqlServer.Types. Local` used to contain a DLL, `vcruntime140.dll` but no longer has it. Because some machines have this DLL installed locally, such as via a runtime, it worked on some environments. But not on others.

I'd bet this is the cause of your issue.

We solved this by including the DLL als a native dependency. Its a breaking change. No idea if it was on purpose.

**Comment by jerry651108** [comment]
I also faced the issue when I ran my .net 7 application published into K8s container environment. The error message was "Required functionality is not implemented on this platform (Linux 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 - X64)".

dotMorten.Microsoft.SqlServer nuget  could not solve the issue. Because it didn't support some functions, for example, call STLength() function in Microsoft.SqlServer.Types.dll (version 160.1000.6) to calculate distance (meters).

I want to re-write the original codes by using Nettopologysuite but it didn't support all the functions in Microsoft.SqlServer.Types.dll.

Does anyone have any other suggestions? Thank you.

**Comment by ErikEJ** [comment]
Where can users address issues with Microsoft.SqlServer.Types ?

**Comment by Ansssss** [comment]
@cheenamalhotra I second ErikEJ's question. Is the official position not to support this on Linux, or is this not the right place to report this bug?

**Comment by David-Engel** [comment]
This isn't the repo for that package. I would try the Contact owners link on the [NuGet package](https://www.nuget.org/packages/Microsoft.SqlServer.Types).

![image](https://github.com/user-attachments/assets/70cf9010-9745-45dc-9159-7f6d30214c8c)

**Comment by jerry651108** [comment]
I ran my .net7 app in K8s environment also faced the same issue. (error message: Required functionality is not implemented on this platform (Linux 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 - X64).)

My app used a lot of functions/methods in Microsoft.SqlServer.Types.dll (160.1000.6 ). So using dotMorten.Microsoft.SqlServer.Types nuget  didn't solve the issue.

Does anyone have any other suggestions? Thank you.

**Comment by BartjeD** [comment]
Again: We included the DLL as a native dependency, not via a NuGet reference.

![Image](https://github.com/user-attachments/assets/d7a17eb3-8fee-4b01-9519-2e4f84b47994)

`<Content Include="NativeDependencies\*.dll" TargetPath="%(OutDir)\%(Filename)%(Extension)">
	<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>`

**Comment by jerry651108** [comment]
@BartjeD 
Thank you for your explanation. I am sorry that I misunderstood.
However, just like Ansssss said...
I also tried to include the vcruntime140.dll to my project. There was still an error message:  Required functionality is not implemented on this platform (Debian GNU/Linux 12 (bookworm) - X64).
