### ISSUE TITLE
A breaking change was implemented in a recent update to the Microsoft.Data.SqlClient package

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/SqlClient#2267]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/A-breaking-change-was-implemented-in-a-r/10537680)._

---
[regression]
It was due to a breaking change was implemented in a recent update to the Microsoft.Data.SqlClient package: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#encrypt-true.  After finding this article I was able to resolve the issue and reapply the updates.

---
#### Feedback Bot on 12/11/2023, 03:20 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by kf-gonzalez** [comment]
A SqlException will be thrown every time a certificate is not used when Encrypt=True is used  by default, that is the new designed behaviour. This has been changed since V4. Follow the steps documented on https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#encrypt-true.

For more information here is a FAQ about it

https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions#12-i-have-upgraded-microsoftdatasqlclient-to-version-400-but-am-not-able-to-open-a-connection-which-was-working-in-a-previous-version
