### ISSUE TITLE
System.Data.SqlClient 4.6.1 vs System.Data.SqlClient 4.7.0 

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [dotnet/SqlClient#227]
In my Azure Function (V2) with System.Data.SqlClient 4.6.1 everything works fine, but with System.Data.SqlClient 4.7.0  I get 'System.Data.SqlClient is not supported on this platform.' when 
 my function is trying to connect to Azure SQL db.

everything else stays the same.

what the hell is going on ???

Yours,
Esa Poutanen MOST Digital Oy
esa.poutanen@mostdigital.fi
+358-40-5538866

**Comment by EsaHeikkiPoutanen** [comment]
resolved using older version

**Comment by cheenamalhotra** [comment]
Hi @EsaHeikkiPoutanen 

Thanks for reporting the issue, I was able to reproduce it and will reopen for further investigation.
For now you may proceed with older version that is working fine.

**Comment by Rychu-Pawel** [comment]
The issue made it to 4.8.0 preview. Could you please ensure us it is a bug, not a permanent change? :)

**Comment by EsaHeikkiPoutanen** [comment]
Well, I had to start using older version (4.6.1) of this to get things working, so I suppose it’s a bug, or are You trying to make people not using this ?

Cheers,
Esa

Esa Poutanen
Software Robotics Developer
MOST Digital Oy
esa.poutanen@mostdigital.fi<mailto:esa.poutanen@mostdigital.fi>
[cid:image001.png@01D58432.4ECCE620]
www.mostdigital.fi<http://www.mostdigital.fi/>

**Comment by yukiwongky** [comment]
@EsaHeikkiPoutanen I still have not been able to find the root cause for this, but seems like Azure Function isn't able to move the correct dll into the bin folder at build time. Meanwhile there is a workaround post [here](https://github.com/Azure/Azure-Functions/issues/1370), and that is to add these lines in your csproj file.
```
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="copy $(OutDir)$(ProjectName).deps.json $(OutDir)bin\function.deps.json" />
</Target>
<Target Name="PostPublish" BeforeTargets="Publish">
  <Exec Command="copy $(PublishDir)$(ProjectName).deps.json $(PublishDir)bin\function.deps.json" />
</Target>
```

**Comment by cheenamalhotra** [comment]
Hi @EsaHeikkiPoutanen 

The issue was identified with Azure Functions SDK "**Microsoft.Net.SDK.Functions**" version **1.0.29**. Newer versions of SDK (currently in Beta and Preview) have fixed the problem and now work properly with dependent libraries.

You can take a look at an example repository for Microsoft.Data.SqlClient and Azure Functions (all runtime versions), details posted [here](https://github.com/dotnet/SqlClient/issues/289#issuecomment-559625453). The same should work for System.Data.SqlClient 4.7.0, please feel free to re-open if you face any problem.
