### ISSUE TITLE
SQL Server Pre-Login Handshake (error: 31 - Encryption(ssl/tls) handshake failed)

### ISSUE THREAD

**Issue by Mehranh** [dotnet/SqlClient#2272]
Our project, which is built on .NET 8, is encountering an issue when trying to connect to our SQL server (version 11.0.5058). The Docker file for our project is as follows:

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80
Copy . .

RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf

RUN cat /etc/ssl/openssl.cnf

ENTRYPOINT ["dotnet", "Api.dll"]
```

when I want to open a SQL connection I get this error :

`System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)`

We’ve tried all the solutions mentioned in [this GitHub issue](https://github.com/dotnet/SqlClient/issues/222), but unfortunately, none of them have resolved our problem.

We’re hoping you might be able to assist us in resolving this issue. Thank you in advance for your help!e

**Comment by David-Engel** [comment]
The encryption handshake failed. Most likely due to no common encryption algorithms between the client and the server. SQL Server 11.0.5058 is not an up-to-date SQL Server 2012 instance. It'll be hard to tell what old algorithms are configured on that side. Modern containers tend to disable older, less secure algorithms, by default.

It would be helpful if you included details like what SqlClient library version you are using. The OS version SQL Server is running on. What does your openssl.cnf look like? What connection string options are you using?

**Comment by David-Engel** [comment]
Looks like the latest comment on [#2242](https://github.com/dotnet/SqlClient/issues/2242#issuecomment-1858390282) might be a solution for you.

**Comment by Mehranh** [comment]
> Looks like the latest comment on [#2242](https://github.com/dotnet/SqlClient/issues/2242#issuecomment-1858390282) might be a solution for you.

Thanks, it works for me
