### ISSUE TITLE
Powershell script not finding Microsoft.Data.SqlClient.SNI.dll but works under Visual Studio Code

### ISSUE THREAD

**Issue by TRCarbone** [dotnet/SqlClient#2287]
I have a PowerShell script using Microsoft.Data.SqlClient. I have the following DLLs in the same folder as the ps1 file:

Azure.Core.dll
Azure.Identity.dll
Microsoft.Data.SqlClient.dll
Microsoft.Data.SqlClient.SNI.dll
Microsoft.Identity.Client.dll
Microsoft.IdentityModel.Abstractions.dll

I am loading them all (except for the SNI DLL) with Add-Type. If I try Add-Type with that file, I get a Bad IL error.

The script tries to connect to a database. When I run the script in Visual Studio Code with the PowerShell Extension (my development environment), it works just fine.

If I then run the ps1 in just PowerShell it fails with the error:

Unable to load DLL 'Microsoft.Data.SqlClient.SNI.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

It seems that there is some difference in where SqlClient is looking for the DLL. Everything I read just says it needs to be in the same folder as the ps1 file.

Any ideas?

**Comment by DavoudEshtehari** [comment]
This is about the dependency resolution since Microsoft.Data.SqlClient is a multi-targeted driver and I'd suggest using the latest version of [SQL Server](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fsql%2Fpowershell%2Fdownload-sql-server-ps-module%3Fview%3Dsql-server-ver16&data=05%7C02%7Cv-deshtehari%40microsoft.com%7C8645ed189f694c1012b508dc0e133083%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638400722782967883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NKcV5Ipxc8A54YQfXqDCMbFfAhuKepG53o0SKlAG6l8%3D&reserved=0) module or looking into the [similar issues](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2FSqlClient%2Fissues%3Fq%3Dis%253Aissue%2Bin%253Atitle%2Bpowershell%2B&data=05%7C02%7Cv-deshtehari%40microsoft.com%7C8645ed189f694c1012b508dc0e133083%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638400722782950359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ieCRrFwCSCBd8U9EXLQ0B8MZU6EHhsmvnY%2B7sHS8i6U%3D&reserved=0) for a possible workaround.

**Comment by kf-gonzalez** [comment]
This issue is a PowerShell related issue. Feel free to comment if there is more info available in the future.
