### ISSUE TITLE
Vulnerability Issue CVE-2024-0056 : System.Data.SqlClient@4.8.6

### ISSUE THREAD

**Issue by yogeshbajpai2024** [dotnet/SqlClient#2313]
We have upgraded to latest version 4.8.6 of System.Data.SqlClient as recommended but still shows the issue of vulnerability with CVE-2024-0056.
We are using dotnet 6 SDK and runtimes in our solutions, please let us know by when this issue will be resolved in next version of System.Data.SqlClient

Issue Details: CVE-2024-0056

Explanation: The `Microsoft.Data.SqlClient` and `System.Data.SqlClient` packages are vulnerable due to Information Exposure. The `ConsumePreLoginHandshake()` method of the `TdsParser` class mishandles encryption options between clients and database servers. An Adversary-in-the-Middle (AitM) attacker can potentially leverage this behavior to obtain the plaintext credentials used to establish database connections.
Detection: The application is vulnerable by using this component.
Recommendation: We recommend upgrading to a version of this component that is not vulnerable to this specific issue.

**Comment by kf-gonzalez** [comment]
> We have upgraded to latest version 4.8.6 of System.Data.SqlClient as recommended but still shows the issue of vulnerability

Please explain how the vulnerability is still shown, snapshots or repros would be appreciated. 4.8.6 of System.Data.SqlClient  does not contain any vulnerability issue.

**Comment by yogeshbajpai2024** [comment]
The issue is detected since NuGet Package containing DLL's file has older version that are not upgraded to latest NuGet Package. 

If we look at file version of bundled DLL's inside the NuGet Package, those have the older versions:

Path : system.data.sqlclient.4.8.6\lib\net451\System.Data.SqlClient.dll
**version : 4.6.24705.01**
Path : system.data.sqlclient.4.8.6\lib\net46\System.Data.SqlClient.dll
version : 4.6.24705.01
Path :system.data.sqlclient.4.8.6\runtimes\unix\lib\netstandard1.3\System.Data.SqlClient.dll
**4.6.24705.01**

This is why SonaType Scans are reporting CVE-2024-0056 for system.data.sqlclient.4.8.6.nupkg as it contains vulnerable code.
For NuGet analysis, the version you see in the Version Explore is based on the [[Pecoff](https://community.sonatype.com/t/enhancements-to-nuget-net-scanning-in-nexus-lifecycle/4569)] (PE = Portable Executable, COFF = Common Object File Format) files. 

You can review below document for more details.
https://help.sonatype.com/en/nuget-application-analysis.html

can you review the versions inside the package and correct for the same package?

**Comment by H-Yeo** [comment]
This looks like it belongs to a different team @kf-gonzalez , specifically for System.Data.SqlClient published on Nuget.org.
Perhaps @yogeshbajpai2024 you can move to Microsoft.Data.SqlClient if possible?

**Comment by David-Engel** [comment]
I asked the .NET team that builds System.Data.SqlClient about the versioning.

**Summary:** SonaType shouldn’t be trying to infer DLL versions from package version information in the CVE and should remove the false positive.

**Details:**

> How should scanners detect vulnerabilities in deployed runtime DLLs?

Looking at individual DLLs is fine, but scanners will typically want to look at DLL hashes, not versions. That way they can differentiate lib/net451/foo.dll vs lib/netcoreapp2.1/foo.dll, etc. In this case, SonaType's vulnerable DLL list improperly contains an entry marking the lib/net451/System.Data.SqlClient.dll assembly as vulnerable, when it is in fact not vulnerable.

This is why we tell companies making vulnerability scanners to look at packages instead of assemblies. Because if all they have is package information, then the only thing they can reliably scan is packages. It's incorrect for them to take package information and to try to derive assembly information automatically from that, as it leads to the problem you pointed out above. [internal DLL versions don’t match the package version]

They can make a list of vulnerable DLLs if they really want, but it requires human involvement. It can't be autogenerated from the vulnerable packages list. Unfortunately it appears that SonaType has done just that. 

To what's perhaps your deeper question [I asked why some DLL versions don’t appear incremented from package version to package version], we don't update every DLL when we release new packages. We only update DLLs which are vulnerable. For DLLs which are not vulnerable (perhaps because the vuln was fixed in Framework), we usually perform a harvesting process, where the DLL is simply plucked from an older package and inserted into the newer package. The file version, digital signature, etc. remain the same since the DLL is byte-for-byte identical.

That harvesting process largely stopped in the net5.0 timeframe, I believe, and newer packages have a more consistent assembly versioning story.

**Comment by JRahnama** [comment]
Closing the issue as it is external to this driver.

**Comment by ktrace2** [comment]
Also experiencing CVE-2024-0056 from a Wiz vulnerability scan even tho 4.8.6 is installed.

Wiz shows this:

> The library System.Data.SqlClient version 3.1.39 was detected in Nuget library manager located at /home/username/application-name/System.Data.SqlClient.dll and is vulnerable to CVE-2024-0056, which exists in versions <4.8.6.
> 
> The vulnerability was found in the Github Security Advisory with vendor severity: High.
> 
> The vulnerability can be remediated by updating the library to version 4.8.6 or higher, using dotnet add package System.Data.SqlClient.

Looking deeper is seems System.Data.SqlClient.dll inside the 4.8.6 nuget package has a product version of 3.1.39 which is causing Wiz to think this is unpatched.

**Comment by VladislavDubrovenski** [comment]
mend-bolt-for-github flags it as well: 

Dependency Hierarchy:

❌ system.data.sqlclient.4.8.6.nupkg (Vulnerable Library)
Found in base branch: 

Vulnerability Details
Microsoft.Data.SqlClient and System.Data.SqlClient SQL Data Provider Security Feature Bypass Vulnerability

Publish Date: 2024-01-09

URL: [CVE-2024-0056](https://www.mend.io/vulnerability-database/CVE-2024-0056)

**Comment by cbutterfield24** [comment]
![image](https://github.com/dotnet/SqlClient/assets/169391351/b670aa9d-25d0-437a-8b43-76e51b7205ce)

the 4.8.6 package version is getting erroneously flagged by BlackDuck as well because of product version 3.1.39
