### ISSUE TITLE
5.2.0: using sqlConnection.FireInfoMessageEventOnUserErrors = true generates "Object reference not set to an instance of an object." exception

### ISSUE THREAD

**Issue by BertDeHaes** [dotnet/SqlClient#2388]
### Describe the bug
When using sqlConnection.FireInfoMessageEventOnUserErrors = true, a "print" sql command always throws an exception

**Exception message:**
Object reference not set to an instance of an object.

**Stack trace:**
   at Microsoft.Data.SqlClient.SqlCommand.GetCurrentBatchCommand()
   at Microsoft.Data.SqlClient.TdsParser.FireInfoMessageEvent(SqlConnection connection, SqlCommand command, TdsParserStateObject stateObj, SqlError error)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at SqlClientBug.Program.Main(String[] args) in E:\NAS2\COBEMAR\2022\dotNet\SqlClientBug\Program.cs:line 31

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
namespace SqlClientBug
{
   internal class Program
    {
        static void Main(string[] args)
        {
            SqlConnectionStringBuilder sb = new();

            sb.TrustServerCertificate = true;
            sb.DataSource = ".";
            sb.InitialCatalog = "tempdb";
            sb.IntegratedSecurity = true;
            sb.ApplicationName = "SqlClientBug";
            
            using SqlConnection sqlConnection = new(sb.ConnectionString);
            sqlConnection.FireInfoMessageEventOnUserErrors = true;
            sqlConnection.Open();
            using SqlCommand cmd = sqlConnection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.Text;
            cmd.CommandText = "print 'OK';";
            try
            {
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(ex.Message);
                Console.Error.WriteLine("--------------------");
                Console.Error.WriteLine(ex.StackTrace);
            }
        }
    }
}
```

### Expected behavior
As in previous versions: no Exception

### Further technical details
Microsoft.Data.SqlClient version: 5.2.0
.NET target: .NET 8.0
SQL Server version: SQL Server 2022
Operating system: Windows 11

**Additional context**
No problem when using Microsoft.Data.SqlClient version 5.1.5

**Comment by PiotrZimniakSP** [comment]
We have the same problem.
Additional information:
The error occurs only when `commandType != procedure` and only when the passed query returns a warning or error.
Generally, from what we have observed, the error is caused by the uninitialized array `_rpcArrayOf1` in `SQLCommand` class, which is used in this case to return `SQLBatchCommand` for the `SqlException.CreateException`  method.
The auxiliary query on which this error occurs:
`SELECT COUNT(Floor) C FROM (VALUES (1), (NULL), (2)) X (Floor)`

**Comment by Wraith2** [comment]
Ok. I debugged through it and understand the situation now. The library only needs to use an RPC object internally if there are parameters and in this case there aren't so it follows a path that simply sends the text without first building any sort of RPC. It'd be good to get this sort of breakdown as part of the fix so those of us following along at home can understand why the fix works.

It does raise a question or what happens if you try to setup a BatchCommand with a set of commands that have no parameters, would errors be reported correctly or crash?

**Comment by mariusbancila** [comment]
I have the same problem. When should we expect a release that we can use?
