### ISSUE TITLE
Transitive CVE in System.Runtime.Caching

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/SqlClient#2908]
can you update to 8.0.1 and release a new nuget

**Comment by Xyloto91** [comment]
Have same issue due to Trivy vulenrability scan, pls update this so we don't need to update transitive dependency.

**Comment by jaskaransinghdr6j** [comment]
+1 being flagged by Anchore and other GH feeds

**Comment by mungojam** [comment]
It seems like in general if the Microsoft.Data.SqlClient package were updated to use v8.x rather than v6.x of various dependencies, all this noise would go away as the sub-dependencies like Microsoft.IdentityModel.Protocols.OpenIdConnect have been updated so that they just rely on the .net core provided versions instead.

**Comment by weldevops** [comment]
We use this package in our most widely used library and functionally every one of our services is screaming about vulnerabilities.

Is there a rough estimate when the updates might be released or should we override this dependency so long as it may be a while?

Can we assist with the patching at all?

**Comment by roji** [comment]
Everyone, you can take a direct dependency on System.Runtime.Caching 8.0.1 from your project; there's no need to wait until SqlClient releases.

**Comment by benrr101** [comment]
It looks like we updated the dependency was updated in v6, but will need to be backported to previous, supported releases.

**Comment by David-Engel** [comment]
Backport tracking issue: #2935
