### ISSUE TITLE
AzureKeyVaultProvider should move to the latest Azure KeyVault Libraries

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/SqlClient#294]
### Describe the bug
AzureKeyVaultProvider should move to the latest Azure KeyVault Libraries.

https://www.nuget.org/packages/Azure.Security.KeyVault.Keys
https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets

**Comment by Petermarcu** [comment]
@AlexGhiondea

**Comment by Petermarcu** [comment]
@David-Engel @cheenamalhotra

**Comment by m1nkeh** [comment]
but for why.. is there actually something which will be fixed, or just for the fun? :)

**Comment by heaths** [comment]
Azure.Security.KeyVault.* packages will be our focus going forward, including any new features that the Key Vault service provides. It's also built around Azure.Core which has unified tracing, logging, retries, and more built into the pipeline. We also have a cross-language focus to provide consistency across .NET, Python, JavaScript (both Node and in-browser), and Java, with more languages on the horizon so that, if you need to interact with other languages or frameworks, you have a similar developer experience.

**Comment by kmscode** [comment]
The [Microsoft.Azure.KeyVault package](https://www.nuget.org/packages/Microsoft.Azure.KeyVault/) has been officially deprecated for a number of months now (coming up on a year if it was deprecated when the last build was posted).

Would be nice to have fewer dependencies and everything on current versions. Thanks!

**Comment by David-Engel** [comment]
Azure.Core (the main dependency under the new AKV packages) only supports .NET Framework 4.6.1 and up. Microsoft.Data.SqlClient 2.1 supports .NET Framework 4.6 and up. In order to move to the new libraries, SqlClient has to make a breaking change, dropping support for 4.6.0. So it will only happen on a major version bump.
