### ISSUE TITLE
In ExecuteReader, how to know when the query return 0 or its throwing exception

### ISSUE THREAD

**Issue by abratv** [dotnet/SqlClient#3080]
### Is your feature request related to a problem? Please describe.
This long time issue, basically until we call Read, HasRows already return false when the query throwing exception
```
if (reader.HasRows) //The query should throw exception but HasRows simply return false
{
    while (reader.Read()) //When you call this, then the exception is thrown
    {
```

What is the recommendation to tackle the issue?

other than, don't call HasRows

**Comment by abratv** [comment]
```
DELETE SI
FROM TableA SI
WHERE SI.X = 1000

MERGE INTO xxxx

OUTPUT COALESCE(inserted.Id, deleted.Id) as Id,
	$ACTION as Op;
```

Simplified due privacy etc

same issue from 14 years ago
https://www.experts-exchange.com/questions/26336589/SqlCommand-ExecuteReader-not-returning-any-error-even-when-there-is-an-error-in-the-query.html

So i doubt you will fix the behavior, but maybe give us a new field like IsError to indicate that there is error in the query

**Comment by David-Engel** [comment]
What's the purpose of `if (reader.HasRows)`? I mean, why not just say `if (reader.Read()`? Or use a boolean to track if any rows were actually read? HasRows isn't meant to tell you if your query errored. It just tells you the current state of the reader. If there was an error, there are no rows. You have to Read() to get the error.

As for adding `IsError`, even that likely wouldn't behave as you'd probably want it to and I don't see what benefit it would bring over just calling `Read()` to get the error(s). There could be multiple result sets and multiple errors. You truly need to process the entire set of results to see them all. The driver won't even know about some errors until it encounters them as results are processed. This is a common misconception users have when processing results. Here's a relatively simplistic example of processing multiple results that contain multiple errors in the response:

```
        using var connection = new SqlConnection(connectionString);
        connection.Open();

        var command = new SqlCommand("select '1'; select 1/0; select '2'; select 2/0; select '3'", connection);
        using var reader = command.ExecuteReader();
        do
        {
            try
            {
                while (reader.Read())
                {
                    Console.WriteLine(reader.GetString(0));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error processing results: {ex.Message}");
            }
        } while (reader.NextResult());
```

Output:
```
1
Error processing results: Divide by zero error encountered.
2
Error processing results: Divide by zero error encountered.
3
```

**Comment by abratv** [comment]
Well if you read the documentation

Call "HasRows" so I don't have to call "Read", now you are telling me to just call "Read" which defeat the purpose of "HasRows"

![Image](https://github.com/user-attachments/assets/0a9790f2-11b4-4a5d-8425-c8f9574f01b7)

**Comment by David-Engel** [comment]
You are quoting documentation from a different library. The [SqlClient documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqldatareader.hasrows?view=sqlclient-dotnet-standard-5.2) simply states:

 ![Image](https://github.com/user-attachments/assets/80f9968e-e01b-46f0-9d3a-0c01af95efd0)

Even documentation for the parent object, DbDataReader, says the same thing:

![Image](https://github.com/user-attachments/assets/7c7f05c3-4b16-4ddc-8f5e-598e31a33214)

Due to the underlying differences of a DataTable versus consuming the results of a SqlCommand, it's not unreasonable for the implementations to have some differences, too. The full results of a `SqlCommand.ExecuteReader` call are not available in memory all at once. You need to consume the results via `Read()` and `NextResults()` (which streams them from the server) in order to know what data is available and what errors there might be in the results.

In the context of a `SqlDataReader`, I agree that `HasRows` has limited value. But `SqlDataReader` is just implementing what is in `DbDataReader`, which was designed to support multiple different scenarios.

The current behavior of `HasRows` in `SqlDataReader` is definitely by design. You need to process all the results, as in my previous code example, and can't just rely on `HasRows` if you want to see errors.
