### ISSUE TITLE
Add NTLM authentication to SqlClient

### ISSUE THREAD

**Issue by ebekker** [dotnet/SqlClient#31]
While #4198 added support for integrated authentication when a client runs on a domain-joined host, it can be quite useful to support NTLM-based Windows authentication from a non-domain-joined host, especially in today's serverless or container environments.

I know this is possible simply at the protocol level (TDS) because this has been supported in the [jTDS](https://sourceforge.net/p/jtds/code/HEAD/tree/branches/jTDS%201.3%20%28stable%29/src/main/net/sourceforge/jtds/jdbc/TdsCore.java#l2238) JDBC driver for quite some time.

The goal is to be able to connect to a SQL Server instance using Windows Authentication from a non-domain-joined host (and also, not necessarily a Windows host), simply by providing the connection credentials in the connection string (domain, username, password).  Is this possible today?

**Comment by FireInWinter** [comment]
Any chance of this being implemented anytime soon?  I was really hopeful for a little while when it was added for SqlClient v1.1.0 as a ToDo, but then it was removed and seems to have been put on the back burner.

At this point .net core is a bad development choice for developers on Mac or Linux.  I've been suggesting they use DBeaver (or the Java based DB tool of their choice) to do database design.  Since the MS JDBC SQL driver has added NTLM auth, we can manage their permissions using AD and groups.  If we suggest they use Azure Data Studio, then we have to create SQL logins for them and try to manage the passwords (sort of like with Windows NT 3.1 before Domains - per server), not a good options when you have over a thousand databases ranging from 1GB to 50TB.

**Comment by ebekker** [comment]
If you're looking for this support for Linux, I was able to roll my own solution to this issue with the help of native Kerberos tooling, you can find the details here:  https://github.com/zyborg/Zyborg.AWS.Lambda.Kerberos

It can pby be adapted to MacOS as well using a similar approach.

**Comment by andreabedini** [comment]
Can I suggest we write in the FAQ that NTLM authentication on Linux is not supported? Otherwise I am driven to think I can start using .NET on Linux when I actually cannot (apologies, this might sound like a rant and probably it just is, I am frustrated after having spent a couple hours figuring out why I couldn't connect, this after spending the night figuring out how to make FSharp SqlProvider work (which it won't because fsharp type providers don't work on Linux)).

_Let's try again_

Could we clarify the necessary steps to make this happen? Perhaps someone will be able to offer a contribution and speed things up.

<3

**Comment by FireInWinter** [comment]
@andreabedini Of course you can always skip to Java and use NTLM authentication just fine, since the MS SQL JDBC driver DOES support NTLM authentication by giving it the user and password. /sarcasm

Some people try to claim that Kerberos support is the same as NTLM support, but it isn't.  There is a LOT more work outside of what DBAs/Devs can do to get Kerberos to work.  Also, based on the effort it took the JDBC driver team to implement NTLM, it isn't a huge project, just very important to a lot of us.

For a developer working on this, a good starting place would be to see how they implemented it on the Java side.  Looks like they released NTLM auth there about a year ago, but I think they had a bug that didn't get fixed for me until 8.2.0 (earlier this year).  Now we don't have to create SQL Logins for our developers on Macs(or the mess of trying to manage their passwords on multiple servers).  Of course we don't support Azure Data Studio on Macs, since that uses .net core and doesn't support NTLM.

I really hope a developer is soon willing to take this project on.  I would, but I'm mainly a DBA and have only recently started learning programming.

**Comment by brianlagunas** [comment]
I'm not creating a PR until a conversation is had with the maintainers. They may not want this feature added at all ,and may not accept a PR.

**Comment by JRahnama** [comment]
@brianlagunas as @ErikEJ mentioned, as  an open source project we always welcome contribution from the community. If the feature is high in demand and many are requesting it we would love to have a PR prepared so we can go over it and start reviewing it as soon as possible.  I call our PM @David-Engel and our team lead @cheenamalhotra to get their opinion on this matter as well.

**Comment by David-Engel** [comment]
NTLM is not a secure protocol. Research it to understand the security resistance to supporting it.

It was only added to the JDBC driver in order to help the large, _existing_ base of applications that relied on it to move off of older, less secure drivers like jTDS. It was added with the caveat that documentation would clearly state that NTLM auth is not secure and not recommended for use. Since SqlClient comes from a lineage that has never had NTLM username/password auth (different from integrated NTLM auth), it's a lot harder to justify the security risks around adding it.

Even if someone else contributed the PR, there would be strong resistance from the security team to accepting the feature.

We do understand that Kerberos is not as easy to configure and use from a user perspective. I wish there was an easy way to solve that problem.

Regards,
David

**Comment by 3dbrows** [comment]
> I may consider publishing my build publicly so all can benefit from it. I would need to get clearance from my company first.

@brianlagunas , I was wondering if you had published your build publicly? Is this you? https://www.nuget.org/packages/IG.Data.SqlClient/

If so, does the connection string need to specify NTLM somehow?

**Comment by capcom923** [comment]
Thanks @brianlagunas & @3dbrows , it works fine both in Windows and Linux after installed IG.Data.SqlClient package. I think we should merge this great change to the SqlClient.

**Comment by brianlagunas** [comment]
@capcom923 I agree. There should be a way to opt into this behavior instead of us having to maintain a separate package for it.

**Comment by capcom923** [comment]
> @capcom923 I agree. There should be a way to opt into this behavior instead of us having to maintain a separate package for it.
Yes, and this separate package seems hard to work with ORM since it is not merged.
For example, given a project which uses EntiryFrameworkCore as ORM, the IG.Data.SqlClient is not working any more after installed. The UID and PWD will not be used when set intergrated security = true. The connection will still use the identity of the running application.
So, is that possible to make IG.Data.SqlClient work with EFcore v5.0.17?

**Comment by capcom923** [comment]
> @capcom923 I agree. There should be a way to opt into this behavior instead of us having to maintain a separate package for it.

Yes @brianlagunas , and this separate package way seems hard to work with ORM.
For example, given a project which used EntiryFrameworkCore as ORM, the IG.Data.SqlClient is not working any more after installed. The UID and PWD will not be used when set intergrated security = true. The connection will still use the identity of the running application.
So, is that possible to make IG.Data.SqlClient work with EFcore v5.0.17?

**Comment by brianlagunas** [comment]
@capcom923 I have made the code public so feel free to grab what you need and place it in your own fork 

https://github.com/RevealBi/IG.Data.SqlClient

**Comment by brianlagunas** [comment]
To add this functionality yourself, add a package reference to SharpCifs.std. Then in the `netcore/Microsoft.Data.Sql/Data/SqlClint/TdsParser.SNISSPIData`, use this code instead

```cs
        private void SNISSPIData(byte[] receivedBuff, uint receivedLength, ref byte[] sendBuff, ref uint sendLength)
        {
            if (_connHandler.ConnectionOptions.IntegratedSecurity
                && !string.IsNullOrEmpty(_connHandler.ConnectionOptions.UserID) && !string.IsNullOrEmpty(_connHandler.ConnectionOptions.Password))
            {
                if (receivedBuff == null) // first message
                {
                    var type1Message = new SharpCifs.Ntlmssp.Type1Message(); //[review] FLAGS
                    type1Message.SetSuppliedWorkstation(_connHandler.ConnectionOptions.ObtainWorkstationId());
                    sendBuff = type1Message.ToByteArray();
                    sendLength = (uint)sendBuff.Length;
                }
                else // challenged
                {
                    var type2MessageBytes = new byte[receivedLength];
                    Array.Copy(receivedBuff, type2MessageBytes, receivedLength);
                    var type2Message = new SharpCifs.Ntlmssp.Type2Message(receivedBuff);
                    var userId = _connHandler.ConnectionOptions.UserID;
                    var domain = userId.Split('\\')[0];
                    var user = userId.Split('\\')[1];
                    var type3Message = new SharpCifs.Ntlmssp.Type3Message(type2Message, _connHandler.ConnectionOptions.Password, domain, user, _connHandler.ConnectionOptions.ObtainWorkstationId(), type2Message.GetFlags());
                    sendBuff = type3Message.ToByteArray();
                    sendLength = (uint)sendBuff.Length;
                }
            }
            else // the following block is the original.
            {
                if (TdsParserStateObjectFactory.UseManagedSNI)
                {
                    try
                    {
                        _physicalStateObj.GenerateSspiClientContext(receivedBuff, receivedLength, ref sendBuff, ref sendLength, _sniSpnBuffer);
                    }
                    catch (Exception e)
                    {
                        SSPIError(e.Message + Environment.NewLine + e.StackTrace, TdsEnums.GEN_CLIENT_CONTEXT);
                    }
                }
                else
                {
                    if (receivedBuff == null)
                    {
                        // if we do not have SSPI data coming from server, send over 0's for pointer and length
                        receivedLength = 0;
                    }

                    // we need to respond to the server's message with SSPI data
                    if (0 != _physicalStateObj.GenerateSspiClientContext(receivedBuff, receivedLength, ref sendBuff, ref sendLength, _sniSpnBuffer))
                    {
                        SSPIError(SQLMessage.SSPIGenerateError(), TdsEnums.GEN_CLIENT_CONTEXT);
                    }
                }
            }
        }
```

I believe that is all that was needed.

**Comment by capcom923** [comment]
Thank you so much @brianlagunas for your talent code~ Now, I understand that you split the connStr and modify the sendBuff using SharpCifs.
Looking forword your public repo~

**Comment by brandonros** [comment]
@brianlagunas any movement on making a NuGet package for this available/repo public/more fleshed out example? https://www.nuget.org/packages/SharpCifs.Std/ says it's for netstandard1.3, I'm guessing it's a bit out of date for those of us looking to use net6.0+?

**Comment by brianlagunas** [comment]
@brandonros Not really. This hasn't been a high priority for me since it's working for my project, and I don't really want to have to support this for the public 😄. I just don't have the time.

**Comment by cdibbs** [comment]
We're running into this too and also burned too many hours assuming it was supported (it would seem a rather big omission) and trying to figure out what we were doing wrong. This became especially true since early testing showed that `UseDefaultCredentials = true` with HttpClient works fine.

Any movement on it?

**Comment by cdibbs** [comment]
To add motivation, the default OS for aspnet Docker images is Linux, evidenced even in the relative complexity of the tags:

`docker pull mcr.microsoft.com/dotnet/aspnet:8.0` (Linux)

versus longer tags for windows:

```
docker pull mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809
docker pull mcr.microsoft.com/dotnet/aspnet:8.0-windowsservercore-ltsc2022
```

So one would expect the Linux images to be Microsoft's best foot forward. Hopefully this helps make the case to allocate some more resources in a this-erly direction. :-)

**Comment by twsouthwick** [comment]
FYI - I've got a plan and PRs slowly getting merged in to enable this. Please see the https://github.com/dotnet/SqlClient/issues/2253 for details. The general idea is to add a hook at the right point to handle the sspi blobs.

I have a project at https://github.com/twsouthwick/Swick.SqlClient.Sspi that I'll release when it's merged in to enable some easy providers for it. Initially I have one that enables NTLM that I currently need for another project, but wanted to share it in case others have use of it.

**Comment by JeremiasBadilla** [comment]
hi,
I have implemented 
https://github.com/twsouthwick/Swick.SqlClient.Sspi
when trying to perform a savechanges() with Entityframework core, it generates an error.

I am using two connection strings
using var connection = new SqlConnection(_conectionString.Value.ConnectionString)
            {
                SSPIContextProviderFactory = Ntlm.CreateLoggingProvider
            }
                ;
            await connection.OpenAsync();
            using var command = new SqlCommand(sql, connection);
            using var reader = await command.ExecuteReaderAsync();
 _conectionString.Value.ConnectionString = "Server=xxxxxx\xxxxxx;Database=xxxxxx;MultipleActiveResultSets=true;Uid=xxxxxxx;Pwd=xxxxx;" 
(I also tried Integrated Security=True;)

It is essential to have NTLM implementation in the sqlclient because the application will run in a production environment with nginx.
However, implementing the package causes Entity Framework Core (6.0.19) to stop working with another connection string.

("Server=yyyyy\yyyyyyy:1435;Database=yyyyy;MultipleActiveResultSets=true;Integrated Security=True;TrustServerCertificate=True;")

Do you have any ideas how to resolve this scenario?

**Comment by David-Engel** [comment]
Closing this issue in favor of #2253 moving forward.

**Comment by qingdao05** [comment]
@capcom923
You say
it(SqlConnection) works fine both in Windows and Linux after installed IG.Data.SqlClient package in case we only use this package.

I installed IG.Data.SqlClient but it does not work properly with NTLM authentication on Windows.
Could you tell me how you programmed it?

**Comment by roji** [comment]
@qingdao05 please read the above comments before posting a new one (specifically [this one](https://github.com/dotnet/SqlClient/issues/31#issuecomment-944448416)).

**Comment by 0xced** [comment]
Here's a modern version of the patch provided by @brianlagunas if you need NTLM authentication. It doesn't require SharpCifs but requires .NET 9 if you are on Linux or macOS because [#99909](https://github.com/dotnet/runtime/pull/99909) is needed for NTLM authentication to work.

To perform authentication with NTLM, define a connection string with integrated security + domain\user + password.

```csharp
var builder = new SqlConnectionStringBuilder
{
    DataSource = "database.contoso.com",
    IntegratedSecurity = true,
    UserID = @"CONTOSO\alice",
    Password = "hunter2",
};
```

Then build a custom version of `Microsoft.Data.SqlClient` with this patch (must be applied on the `main` branch, currently at commit 17621da1738c10a0784cafbb85560ed12b332863).


```patch
diff --git a/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs b/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
index 5fbfb51..699eadd 100644
--- a/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
+++ b/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
@@ -413,7 +413,7 @@ namespace Microsoft.Data.SqlClient
             // AD Integrated behaves like Windows integrated when connecting to a non-fedAuth server
             if (integratedSecurity || authType == SqlAuthenticationMethod.ActiveDirectoryIntegrated)
             {
-                _authenticationProvider = _physicalStateObj.CreateSSPIContextProvider();
+                _authenticationProvider = _physicalStateObj.CreateSSPIContextProvider(connectionOptions);
                 SqlClientEventSource.Log.TryTraceEvent("TdsParser.Connect | SEC | SSPI or Active Directory Authentication Library loaded for SQL Server based integrated authentication");
             }
 
diff --git a/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs b/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
index 3a709d0..5a9a41d 100644
--- a/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
+++ b/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
@@ -407,7 +407,7 @@ namespace Microsoft.Data.SqlClient.SNI
         [MethodImpl(MethodImplOptions.NoInlining)] // this forces the exception throwing code not to be inlined for performance
         private void ThrowClosedConnection() => throw ADP.ClosedConnectionError();
 
-        internal override SSPIContextProvider CreateSSPIContextProvider()
-            => new NegotiateSSPIContextProvider();
+        internal override SSPIContextProvider CreateSSPIContextProvider(SqlConnectionString connectionOptions)
+            => new NegotiateSSPIContextProvider(connectionOptions);
     }
 }
diff --git a/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs b/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
index 9a4eb45..cd6f732 100644
--- a/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
+++ b/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
@@ -1,6 +1,7 @@
 ﻿#if NET
 
 using System;
+using System.Net;
 using System.Net.Security;
 using System.Buffers;
 
@@ -8,7 +9,7 @@ using System.Buffers;
 
 namespace Microsoft.Data.SqlClient
 {
-    internal sealed class NegotiateSSPIContextProvider : SSPIContextProvider
+    internal sealed class NegotiateSSPIContextProvider(SqlConnectionString connectionOptions) : SSPIContextProvider
     {
         private NegotiateAuthentication? _negotiateAuth = null;
 
@@ -18,7 +19,7 @@ namespace Microsoft.Data.SqlClient
 
             for (int i = 0; i < serverSpns.Length; i++)
             {
-                _negotiateAuth ??= new(new NegotiateAuthenticationClientOptions { Package = "Negotiate", TargetName = serverSpns[i] });
+                _negotiateAuth ??= new(CreateOptions(serverSpns[i]));
                 var sendBuff = _negotiateAuth.GetOutgoingBlob(incomingBlob, out statusCode)!;
 
                 // Log session id, status code and the actual SPN used in the negotiation
@@ -40,6 +41,18 @@ namespace Microsoft.Data.SqlClient
                 throw new InvalidOperationException(SQLMessage.SSPIGenerateError() + Environment.NewLine + statusCode);
             }
         }
+
+        private NegotiateAuthenticationClientOptions CreateOptions(string serverSpn)
+        {
+            var parts = connectionOptions.UserID?.Split('\\');
+            if (parts?.Length == 2 && !string.IsNullOrEmpty(connectionOptions.Password))
+            {
+                var credential = new NetworkCredential(userName: parts[1], password: connectionOptions.Password, domain: parts[0]);
+                return new NegotiateAuthenticationClientOptions { Package = "NTLM", Credential = credential, TargetName = serverSpn };
+            }
+
+            return new NegotiateAuthenticationClientOptions { Package = "Negotiate", TargetName = serverSpn };
+        }
     }
 }
 #endif
diff --git a/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs b/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
index 55e5c51..86ab3e1 100644
--- a/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
+++ b/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
@@ -470,7 +470,7 @@ namespace Microsoft.Data.SqlClient
 
         internal abstract uint DisableSsl();
 
-        internal abstract SSPIContextProvider CreateSSPIContextProvider();
+        internal abstract SSPIContextProvider CreateSSPIContextProvider(SqlConnectionString connectionOptions);
 
         internal abstract uint EnableMars(ref uint info);
 
```

**Comment by 0xced** [comment]
And once #2494 is merged and a new version of `Microsoft.Data.SqlClient` is released, it will be possible to implement NTLM authentication like this.

> [!WARNING]
> Think twice before implementing NTLM though. As @David-Engel [noted](https://github.com/dotnet/SqlClient/issues/31#issuecomment-944448416), NTLM is not a secure protocol.

I needed it because I wasn't able to connect to a server using Kerberos on macOS, getting this error: *Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.* This error eventually disappeared and I won't be using NTLM authentication. I'm documenting my findings here in case it helps someone or, who knows, myself in the future if that error ever comes back.

```csharp
using System;
using System.Buffers;
using System.Data.Common;
using System.Net;
using System.Net.Security;
using Microsoft.Data.SqlClient;

namespace SampleCode;

public class NtlmDataSource(string connectionString) : DbDataSource
{
    protected override DbConnection CreateDbConnection() => new SqlConnection(ConnectionString) { SspiContextProvider = new NtlmSspiContextProvider() };

    public override string ConnectionString { get; } = connectionString;

    private class NtlmSspiContextProvider : SspiContextProvider, IDisposable
    {
        private NegotiateAuthentication? _negotiateAuth;

        protected override bool GenerateContext(ReadOnlySpan<byte> incomingBlob, IBufferWriter<byte> outgoingBlobWriter, SspiAuthenticationParameters authParams)
        {
            var negotiateAuth = GetNegotiateAuthenticationForParams(authParams);
            var sendBuff = negotiateAuth.GetOutgoingBlob(incomingBlob, out var statusCode)!;

            if (statusCode is NegotiateAuthenticationStatusCode.Completed or NegotiateAuthenticationStatusCode.ContinueNeeded)
            {
                outgoingBlobWriter.Write(sendBuff);
                return true;
            }

            return false;
        }

        public void Dispose()
        {
            _negotiateAuth?.Dispose();
        }

        private NegotiateAuthentication GetNegotiateAuthenticationForParams(SspiAuthenticationParameters authParams)
        {
            if (_negotiateAuth is not null)
            {
                if (string.Equals(_negotiateAuth.TargetName, authParams.Resource, StringComparison.Ordinal))
                {
                    return _negotiateAuth;
                }

                // Dispose of it since we're not going to use it now
                _negotiateAuth.Dispose();
            }

            return _negotiateAuth = new NegotiateAuthentication(CreateOptions(authParams));
        }

        private static NegotiateAuthenticationClientOptions CreateOptions(SspiAuthenticationParameters authParams)
        {
            var parts = authParams.UserId?.Split('\\');
            if (parts?.Length == 2 && !string.IsNullOrEmpty(authParams.Password))
            {
                var credential = new NetworkCredential(userName: parts[1], password: authParams.Password, domain: parts[0]);
                return new NegotiateAuthenticationClientOptions { Package = "NTLM", TargetName = authParams.Resource, Credential = credential };
            }

            return new NegotiateAuthenticationClientOptions { Package = "Negotiate", TargetName = authParams.Resource };
        }
    }
}
```

Then use this DbDataSource to perform queries.

```csharp
await using var dataSource = new NtlmDataSource(connectionString);
await using var command = dataSource.CreateCommand("SELECT @@VERSION");
var version = await command.ExecuteScalarAsync();
```

**Comment by twsouthwick** [comment]
>  var parts = authParams.UserId?.Split('\\');
            if (parts?.Length == 2 && !string.IsNullOrEmpty(authParams.Password))
            {
                var credential = new NetworkCredential(userName: parts[1], password: authParams.Password, domain: parts[0]);
                return new NegotiateAuthenticationClientOptions { Package = "NTLM", TargetName = authParams.Resource, Credential = credential };
            }

It appears that we should have a `Domain` property on the auth params separate from the user part of the username. Thoughts?

**Comment by David-Engel** [comment]
> It appears that we should have a `Domain` property on the auth params separate from the user part of the username. Thoughts?

Wouldn't that require MDS to surface a new connection string option? Or parse the username itself (which it wouldn't know it should do)? Why shouldn't the implementation simply parse it from the username (as seen), if it needs to do so? Just trying to figure out what the Domain property should be and where it should come from...

**Comment by twsouthwick** [comment]
My thought is if it's a common thing people will need, parsing the username and adding the property to `SspiAuthenticationParameters` would simplify usage. Deferring that to implementations that need it is fine too
