### ISSUE TITLE
Connection is not properly cleared after a command timeout

### ISSUE THREAD

**Issue by dmytro-gokun** [dotnet/SqlClient#333]
I'm running Microsoft.Data.SqlClient 1.1.0 on .NET Core 3.0 again a local MS SQL Server 2019 Dev Edition (but same issue happens with SQL Azure).

When command execution timeout happens, the connection does not seem to be cleared properly. For example, if the command locked a table, that table remains locked until MS SQL server automatically unlocks by rolling back hanging transaction after some time.

To reproduce:

1) Create a local database named _TestBed_;
2) Create a table in the _TestBed_ database:

```t-sql
CREATE TABLE [Test]
(
    [Id] INTEGER IDENTITY PRIMARY KEY,
    [Name] NVARCHAR(MAX)
)
```

3) Run the following code (you can use the attached [project](https://github.com/dotnet/SqlClient/files/3900508/TimeoutIssue.zip)):

```c#
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;

namespace TimeoutIssue
{
    internal static class Program
    {
        private const string ConnectionString = "Server=(local); Initial Catalog=TestBed; Integrated Security=True";

        private static void Main()
        {
            Task.WaitAll(
                Task.Run(LockTable),
                Task.Run(TryInsert)
            );
        }

        private static void LockTable()
        {
            try
            {
                using var conn = new SqlConnection(ConnectionString);
                conn.Open();
                Console.WriteLine("{0:O}: LockTable Enter. ConnectionId={1}", DateTime.UtcNow, conn.ClientConnectionId);

                using var cmd = conn.CreateCommand();
                cmd.CommandText = @"
                    BEGIN TRANSACTION
                    INSERT [Test] WITH (TABLOCK) VALUES('Name1')
                    WAITFOR DELAY '00:01'
                    COMMIT TRANSACTION
                ";
                cmd.ExecuteNonQuery();

                Console.WriteLine("{0:O}: LockTable Exit", DateTime.UtcNow);
            }
            catch (SqlException ex) when (ex.Number == -2)
            {
                Console.WriteLine("{0:O}: LockTable Timeout", DateTime.UtcNow);
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0:O}: Unexpected exception in LockTable: {1}", DateTime.UtcNow, ex);
            }
        }

        private static void TryInsert()
        {
            try
            {
                Thread.Sleep(TimeSpan.FromSeconds(10));

                while (true)
                {
                    try
                    {
                        using var conn = new SqlConnection(ConnectionString);
                        conn.Open();
                        Console.WriteLine("{0:O}: TryInsert Enter. ConnectionId={1}", DateTime.UtcNow, conn.ClientConnectionId);

                        using var cmd = conn.CreateCommand();
                        cmd.CommandText = "INSERT [Test] VALUES('Name2')";
                        cmd.ExecuteNonQuery();

                        Console.WriteLine("{0:O}: TryInsert Exit", DateTime.UtcNow);
                        return;
                    }
                    catch (SqlException ex) when (ex.Number == -2)
                    {
                        Console.WriteLine("{0:O}: TryInsert Timeout", DateTime.UtcNow);
                        Thread.Sleep(TimeSpan.FromSeconds(10));
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0:O}: Unexpected exception in TryInsert: {1}", DateTime.UtcNow, ex);
            }
        }
    }
}
```

Here's a typical output you will receive:

```
2019-11-28T07:51:43.2464035Z: LockTable Enter. ConnectionId=007a1341-23d6-486a-ba9c-05b40e6f58fb
2019-11-28T07:51:52.9787016Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:52:13.2821142Z: LockTable Timeout
2019-11-28T07:52:22.9795180Z: TryInsert Timeout
2019-11-28T07:52:32.9814216Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:53:02.9841081Z: TryInsert Timeout
2019-11-28T07:53:12.9852900Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:53:42.9865951Z: TryInsert Timeout
2019-11-28T07:53:52.9878703Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:54:22.9890031Z: TryInsert Timeout
2019-11-28T07:54:32.9902235Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:55:02.9907380Z: TryInsert Timeout
2019-11-28T07:55:12.9920148Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:55:42.9922753Z: TryInsert Timeout
2019-11-28T07:55:52.9939088Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:56:22.9934268Z: TryInsert Timeout
2019-11-28T07:56:32.9943738Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:57:02.9951424Z: TryInsert Timeout
2019-11-28T07:57:13.6949977Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:57:43.6946691Z: TryInsert Timeout
2019-11-28T07:57:53.6958744Z: TryInsert Enter. ConnectionId=9f8a1258-5df8-4b58-8303-bdf7895ccfac
2019-11-28T07:58:03.0430395Z: TryInsert Exit
```

As you can see, the table remains locked long after 'LockTable Timeout' timeout happens. Correct me if i'm wrong, but that should not work like that.

**Comment by cheenamalhotra** [comment]
Hi @dmytro-gokun 

I just modified the `using` keyword in your example to blocks and it seems to work fine.

```csharp
// LockTable()
using (var cmd = conn.CreateCommand())
{
    cmd.CommandTimeout = 60;
    cmd.CommandText = @"
        BEGIN TRANSACTION
        INSERT [Test] WITH (TABLOCK) VALUES('Name1')
        WAITFOR DELAY '00:01'
        COMMIT TRANSACTION
    ";
    cmd.ExecuteNonQuery();
}
...
// TryInsert()
using (var conn = new SqlConnection(ConnectionString))
{
    conn.Open();
    Console.WriteLine("{0:O}: TryInsert Enter. ConnectionId={1}", DateTime.UtcNow, conn.ClientConnectionId);

    using (var cmd = conn.CreateCommand())
    {
        cmd.CommandTimeout = 60;
        cmd.CommandText = "INSERT [Test] VALUES('Name2')";
        cmd.ExecuteNonQuery();
    }
    Console.WriteLine("{0:O}: TryInsert Exit", DateTime.UtcNow);
    return;
}
```

**Comment by dmytro-gokun** [comment]
@cheenamalhotra Thanks for you answer.

There're two points:

1)
> I just modified the using keyword in your example to blocks and it seems to work fine

Changing using declarations to using blocks is essentially a no-op. The code is functionally  equivalent in both cases. If it were not, it would mean a serious bug in C# compiler's implementation of using declarations for a really trivial case. I do not believe that's what's happening here, i have bigger faith in C# team :). And this explains why just changing to using blocks w/o changing timeout does not help.

2)
> I also had to increase commandTimeout to 60 to get it working.

Okay, this is what did the trick for you. However, it only works because the delay in the query happens to be 1 minute (WAITFOR DELAY '00:01'). If you increase that delay to 2 minutes, you are back to square one. Besides, manipulating command timeouts to hide a library issue is not a really good idea :). In real life scenarios, you do not have delays specified explicitly. You just have transient network conditions, parallel queries locking tables and so on. That's why we have retries in first hand. And retries should work, not just timeout again and again long after the original transient issue is gone.

> I'll continue to look further if there's any issue or is it just SQL Server's locking mechanism.

Yes, please do. The thing is that we have a serious issue in production (SQL Azure) which is caused by this unexpected behavior: a timeout happens and after that all retries timeout again and again for a half an hour. Restarting the service help immediately, which makes me think that it's that timed out transaction holding a lock and not SQL server itself.

**Comment by cheenamalhotra** [comment]
So here's what's going on internally in the driver in this case:

1. **00:00:00 [LockTable]** 
A connection is created with SQL Server, which opens a transaction internally, INSERTs a row in table, and waits for 1 min locking the table.
2. **00:00:10 [TryInsert]**
A new connection is created that tries to INSERT in the same table, and gets another lock as the table is already locked.
3. **00:00:30 [LockTable]**
SqlCommand times out here (default timeout was 30 seconds) and connection is sent back to pool [_stackNew]. But SQL Server is still holding the lock with WAITFOR on active connection.
4. **00:00:40 [TryInsert1]**
SqlCommand times out here too, sending connection back to pool [_stackNew]. No open transactions on Server side because the driver opened local transaction, and closed it before sending it to pool.
5. **00:00:40 [TryInsert2]**
Creates one more task as the previous attempt failed. The same open connection used by [TryInsert1] is allocated from pool and query is executed, but gets lock from server as table is locked and driver is not receiving any data for that stream.
6. **00:00:60 [LockTable]**
SQL server's WAITFOR is now released, but transaction is still Open. SQL Server waits for driver to listen back for updates, and read the active stream to continue executing the query.
...
After some time (2-4 mins) `CleanupCallback` kicks on the outer pool [_stackNew], and pops and pushes the old connection for [LockTable] to [_stackOld] (_another pool for stale connections_) without touching the parser.
...
After more time (2-4 mins) `CleanupCallback` kicks again on the inner pool [_stackOld] and destroys the unused connections, this time flushing the parser stream and freeing the socket connection with SQL Server.
    - This is when lock is released from the table and INSERT queries can now work normally.

Because the connection stays in pool and keeps the table locked, you have 2 solutions:
- Avoid using transaction statements in queries as driver has no control over them. Let the driver create transaction before executing query and complete query successfully. The data is not committed in database anyway. You can use higher timeouts for commands in case of locks.
- Disable Pooling to avoid connection retention in the driver after query has timed out and free lock from table immediately.

**Comment by dmytro-gokun** [comment]
> Avoid using transaction statements in queries as driver has no control over them. 

Well, the truth it that there are no transaction statements in the real code. The only reason i've added them in the reproduction was to simulate table lock. The real code does a simple insert, but that sometimes times out because of a read happening in parallel (the table in question is really big). And that is not a problem - to handle that we have retries built-in. The real problem is that retries do not help, as the table remains locked after the first timeout.

> 3. 00:00:30 [LockTable]
> SqlCommand times out here (default timeout was 30 seconds) and connection is sent back to pool 
> [_stackNew]. But SQL Server is still holding the lock with WAITFOR on active connection.

I would argue that this connection should not be just sent back to the pool. It should be cleared immediately in order to free server resources its holding.  My connection & command are enclosed in a 'using' and i expect them to be properly cleared when the block exits. The fact that a pool is used internally should have no effect on my code, it's a mere implementation detail. Do not you think so?

**Comment by jamesomitron** [comment]
Hello @dmytro-gokun 
I agree, the timing out of the connection should release the lock on the table. A time out should immediately trigger a self CleanUp (or self destruct) from the pool, so the table is unlocked immediately and other transactions can occur.
@cheenamalhotra, would this be possible?
Also, can there be an auto queue, which will prioritise attempted transactions when the table was locked?

However @dmytro-gokun, slight concern around the approach of using a 
`while (true)`
to handle retries for your inserts in production. It seems like this will not scale. It might be better to use a task scheduler for writes if consistency is not a high priority in your system design. The scheduler will manage the data store writes more efficiently, or you can just use SQL Server's Snapshot Isolation to better manage this (The better solution if you ask me).

**Comment by iz-iznogood** [comment]
Hi all, we are facing the same problems in our systems. We have a sync mechanism that synchronizes data from remote clients to a central server. The process run fine on a 4.6.2 .Net version and does not work at core 2.2 with driver version 1.1.0

We are getting connection timeout exceptions and they seem to linger forever effectively killing the server. The system can serve as much as 6k requests per second although the normal is around 1.5k and it goes in short spikes, meaning they can go from 300 - 2000 in cycles.

I tried disabling the pool but did not help. We do not use any transactions in our code, the setup is simple. 
The only thing that might be problematic is that in 1-2 places I have to call synchronous code inside an asynchronous method, running synchronous query in a constructor for example.

This worked in the past, don't know if it can create problems.

Any help or workaround would be greatly appreciated since this is a production system

**Comment by David-Engel** [comment]
> I agree, the timing out of the connection should release the lock on the table. A time out should immediately trigger a self CleanUp (or self destruct) from the pool, so the table is unlocked immediately and other transactions can occur.

The problem in the repro is the uncommitted transaction that was manually created in the SQL statement. The manual commit to end the transaction never runs because the command times out and the server never moves on to the statement after the WAITFOR because the client has gone away. Thus the lock is not released until the server detects that the connection is closed. The driver does not parse the SQL to know that there is an open transaction. This is why there is client-side transaction handling and embedding transaction statements in your SQL is not recommended.

**Comment by David-Engel** [comment]
> Hi all, we are facing the same problems in our systems. We have a sync mechanism that synchronizes data from remote clients to a central server. The process run fine on a 4.6.2 .Net version and does not work at core 2.2 with driver version 1.1.0
> 
> We are getting connection timeout exceptions and they seem to linger forever effectively killing the server. The system can serve as much as 6k requests per second although the normal is around 1.5k and it goes in short spikes, meaning they can go from 300 - 2000 in cycles.
> 
> I tried disabling the pool but did not help. We do not use any transactions in our code, the setup is simple.
> The only thing that might be problematic is that in 1-2 places I have to call synchronous code inside an asynchronous method, running synchronous query in a constructor for example.
> 
> This worked in the past, don't know if it can create problems.
> 
> Any help or workaround would be greatly appreciated since this is a production system

@iz-iznogood You said connection timeouts, but I assume you meant command timeouts in the context of this issue. Encountering either timeout does not indicate a bug in the driver and is unrelated to this scenario, particularly since you said you tried disabling connection pooling. You're going to need to dig further into your particular issue to determine why your timeouts are occurring. Likely there is locking occurring somewhere that is blocking other clients.

**Comment by cheenamalhotra** [comment]
Closing this issue as per above discussions.
