### ISSUE TITLE
SqlDataReader.Close blocks in SNIReadSyncOverAsync after early breaking from reading large dataset

### ISSUE THREAD

**Issue by jakrivan** [dotnet/SqlClient#34]
SqlDataReader is taking unproportionaly long time to Dispose if you are early breaking enumeration through large data set.

I can observer order of magnitude difference in Dispose time depending on number in top clause in select statement, but regardless of the number of rows actually selected. 

Let's have the following code:

        public static void Test()
        {
            IEnumerable<int> en1 = EnumerateLargeData(1000);
            // log time here
            foreach (int i in en1)
            { }
            // log time here

            IEnumerable<int> en2 = EnumerateLargeData(2000000000);
            foreach (int i in en2)
            { }
            // log time here
        }

        public static IEnumerable<int> EnumerateLargeData(int maxCount)
        {
            using (SqlConnection sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                using (SqlCommand getDataCommand = new SqlCommand("[dbo].[GetLargeData_SP]", sqlConnection))
                {
                    getDataCommand.CommandTimeout = 0;
                    getDataCommand.CommandType = CommandType.StoredProcedure;
                    getDataCommand.Parameters.AddWithValue("@MaxCount", maxCount);

                    using (var reader = getDataCommand.ExecuteReader())
                    {
                        int recordsCount = 0;
                        while (reader.Read())
                        {
                            yield return 1;
                            if (recordsCount++ > 100)
                            {
                                //Here is where issue happens
                                break;
                            }
                        }
                    }
                }
            }
        }

Where SP is selecting data from some very large table:

	CREATE procedure [dbo].[GetLargeData_SP]
		@MaxCount INT
	AS
	BEGIN
		SELECT TOP (@MaxCount)
			[DataPoint]
		FROM 
			[dbo].[LargeDataTable] WITH(NOLOCK)
	END

You will see a very large difference in Dispose time depending on the `maxCount` argument - especially when pulling data over slower netwrok.
In my scenario I'm done fetching data in few hundreds milliseconds but then stuck in Dispose for 2 minutes. Exactly in this stack:

![image](https://user-images.githubusercontent.com/3809076/38944056-2f6f0cc2-4333-11e8-965c-720662314d43.png)

**Comment by WillFM** [comment]
I've ran into the exact same issue. In my case, I'm using LINQ.Take() extension method, (the reader is wrapped into an yielded IEnumerable that is returning a type from the rows being returned). Once the Take() method finishes its enumeration, I have to wait for several minutes before the Readers.Discard() to finally return

Owning assembly: v4.5.2 (.Net Framework Library project)
Calling assembly: net462 (AspNetCore 2.2 core project)


Any updates on this? 

Also has anyone found any potential work-around(s)? I supposed I can implement TOP into my stored procedure, but was hoping to avoid schema changes to the database.

**Comment by jakrivan** [comment]
@WillFM 

I did 2 things to successfully workaround thiss issue (I use them in combination to be on a sure side):

- Explicitly calling SqlCommnad.Cancel when I want to stop enumerating the data
- Decreasing the size of the batch that single command call can return and iteratively calling the tha backend SP (requires you have unique ordered column that you can use to distinguish what data were already returned and what needs to be returned)

Both things however require you to refactor your code and write a method that explicitly hanldes the iteration over the data (so that it can call Cancel or so that it calls iteratively to backend). The second workaround requires change in your SP.

**Comment by David-Engel** [comment]
This is actually by design. The correct behavior of a client talking to SQL Server over TDS is to either Cancel the command or consume the results. In the repro, the driver is cleaning up for the application by consuming the results, which is the safe option since it does not know what the executed statement is doing. Failing to consume the results is unsafe and can result in inconsistent application behavior. Calling Cancel would be a choice the application has to make, if it is safe to do so.

This old blog post talks about failing to consume results from SQL Server with example scenarios:
https://blogs.msdn.microsoft.com/psssql/2008/07/23/how-it-works-attention-attention-or-should-i-say-cancel-the-query-and-be-sure-to-process-your-results/

@jakrivan @WillFM

**Comment by divega** [comment]
@David-Engel new CloseAsync and DisposeAsync APIs are being added to the ADO.NET provider model in .NET Core 3.0. I think these could help avoid blocking in a a future version of SqlClient, when you are able to target .NET Standard 2.1. Perhaps having a general issue in the backlog for implementing the new async surface would be a good idea (unless this already exists).

cc @roji

**Comment by roji** [comment]
> The correct behavior of a client talking to SQL Server over TDS is to either Cancel the command or consume the results. In the repro, the driver is cleaning up for the application by consuming the results, which is the safe option since it does not know what the executed statement is doing. Failing to consume the results is unsafe and can result in inconsistent application behavior. Calling Cancel would be a choice the application has to make, if it is safe to do so.

FWIW the same happens in Npgsql, and I'd expect it to be somewhat standard behavior across database drivers.

@divega we have #113 to track implementation of the new async APIs. However, while close/dispose of the reader could help not block the thread while results are consumed, it would still let the query run to completion, possibly using server and network resources, which isn't ideal. The only way around that would be to trigger cancellation when the reader is disposed, but as @David-Engel wrote, it's not right for the driver to do this since we don't want what's running and whether it's safe to cancel.

My general response to this would be to not request a huge amount of results if one isn't sure they're going to be needed. SQL paging, cursors and similar mechanisms can be used to fetch results in chunks, providing natural "exit" points. Otherwise the application can trigger cancellation itself as mentioned above.

**Comment by FixRM** [comment]
Hi @jakrivan, hi @David-Engel. We have same issue with Microsoft D365 installation. Should we upgrade .NET Framework to latest version, or this issue was not resolved?

**Comment by David-Engel** [comment]
> Should we upgrade .NET Framework to latest version, or this issue was not resolved?

The driver behavior described in this issue is By Design and has not changed. Upgrading won't change anything for you. It's up to the application calling the driver to safely call cancel before closing or the driver will do the only safe thing it can: Consume all results to ensure the server executes everything the application sent in the last command.

**Comment by FixRM** [comment]
Thank you @David-Engel. I will contact MS D365 support.

**Comment by jnm2** [comment]
Even if you do cancel appropriately using the cancellation token passed to SqlDataReader.ReadAsync, this problem still stands.

Repro at https://github.com/dotnet/SqlClient/issues/1065#issuecomment-1262671004.
