### ISSUE TITLE
"Invalid column name" message is not helpful

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/SqlClient#347]
The following error message is not so helpful:
> Invalid column name 'Tenantd'.

I might have hundreds of entities which all have a "TenantId" column. It makes it very difficult to pinpoint the exact source of the problem.

Could the error message be improved to contain more contextual information such as the relevant entity or table?

Cross-reference: /aspnet/EntityFrameworkCore/issues/19158

**Comment by cheenamalhotra** [comment]
Hi @vanillajonathan 

This error is thrown from SQL Server, not built in driver, ref: [MSSQLSERVER_207](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/mssqlserver-207-database-engine-error).

Client drivers generally don't modify error messages if received from Server since error code is attached to it, and modifying error message (e.g. appending table name) would mean throwing incorrect error message for error code 207. We cannot also change error code as that would break driver behaviour and many applications are dependent on these message numbers.

You should open a ticket with SQL Server team instead in this case.

**Comment by vanillajonathan** [comment]
Hi @cheenamalhotra 

Where can I open a ticket with the SQL Server team?
I don't think they're on GitHub.

**Comment by cheenamalhotra** [comment]
Hi @vanillajonathan 

You can open a support issue with Microsoft by checking links from section "**Obtain support from Microsoft**" here: [Support Policy for Microsoft SQL Server](https://support.microsoft.com/en-ca/help/4047326/support-policy-for-microsoft-sql-server)

**Comment by David-Engel** [comment]
@vanillajonathan You can also submit feedback to the SQL Server team at this link: https://aka.ms/sqlfeedback

**Comment by vanillajonathan** [comment]
@cheenamalhotra I am not interested in getting support, I don't have questions. What I have is a feature request to improve the error message to be more helpful.

@David-Engel Thanks. I hope they read that tough, maybe its only for ideas that get enough upvotes.

**Comment by cheenamalhotra** [comment]
David's link is correct one for making a feature request, which you just did. You may continue to follow up there, for progress. We will close the issue at our end.
