### ISSUE TITLE
AccessToken property not present when migrating to Core 3.1  

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/SqlClient#357]
I have installed Microsoft.EntityFrameworkCore.SqlServer 3.1 which iscludes SqlClient 1.0.19269.1

I can no longer access AccessToken property on SqlConnection

`SqlConnection' does not contain a definition for 'AccessToken' and no accessible extension method 'AccessToken' accepting a first argument of type 'SqlConnection' could be found (are you missing a using directive or an assembly reference?
`

**Comment by AndersMalmgren** [comment]
I reopened this

The problem was that 2.2 was named System.Data.SqlClient.SqlConnection

And in 3.1 they have changed to Microsoft.Data.SqlClient.SqlConnection

But I cant find were the reference to System.Data.SqlClient.SqlConnection comes to. I do not have any 2.2 stuff left in the solution. Can you guys shed any light on this?

**Comment by ErikEJ** [comment]
You need to share some code!

**Comment by AndersMalmgren** [comment]
Sure. Here is the relevant code, same code before and after migrating from 2.2 > 3.1

```csharp
            services.AddScoped<DbContext>(p =>
            {
                var token = p.GetService<IMemoryCache>().GetOrCreate("SqlAccessToken", entry =>
                {
                    var ctx = new AuthenticationContext("https://login.microsoftonline.com/" + DirectoryId);

                    var result = ctx.AcquireTokenAsync("https://database.windows.net/",
                            new ClientCredential(ClientId, ClientSecret))
                        .ConfigureAwait(false)
                        .GetAwaiter()
                        .GetResult();

                    entry.AbsoluteExpiration = result.ExpiresOn.AddSeconds(-5);
                    return result.AccessToken;
                });

                var db = p.GetService<EkoDbContext>();
                ((SqlConnection)db.Database.GetDbConnection()).AccessToken = token;

                return db;
            });
```

But more important we had this using `using System.Data.SqlClient;`

After upgrade our packages point to EF Core 3.1 and it has a dependency on SqlClient 1.0.19269.1

But above using still works, but with the exception that AccessToken property is removed. I cant find who is referencing `System.Data.SqlClient` 

If I navtigate from System.Data.SqlClien.SqlConnection I see this

![image](https://user-images.githubusercontent.com/817577/71094606-8acc7200-21ab-11ea-8251-8ebdbb6f0208.png)

**Comment by AndersMalmgren** [comment]
Using resharper I get this

![image](https://user-images.githubusercontent.com/817577/71097354-295ad200-21b0-11ea-8b6f-f9985dad5c19.png)

The 3 first references are to our Integration test project. Its not referenced from the project above. 
The fourth one seems to be used from the problem project 

Though I do not know how to find from which nuget package

![image](https://user-images.githubusercontent.com/817577/71097587-7c348980-21b0-11ea-90e4-a4c2832a4f3b.png)

**Comment by cheenamalhotra** [comment]
Hi @AndersMalmgren 

In order to work with Microsoft.Data.SqlClient with EF Core 3.1, all namespace require changes in client applications as documented in [porting cheat sheet](https://github.com/dotnet/SqlClient/blob/master/porting-cheat-sheet.md).

For why `System.Data.SqlClient` namespace is also available in package hierarchy, it could be due to the fact that not all libraries you've referenced have migrated to using Microsoft.Data.SqlClient yet. If expected otherwise, I would recommend opening issue with EF Core or with respective API owners.

**Comment by AndersMalmgren** [comment]
I do not have any of above packages referenced in this project though (But in the solution) so it seems very strange that it did not complain about this.

**Comment by cheenamalhotra** [comment]
Please be aware that both `System.Data.SqlClient` and `Microsoft.Data.SqlClient` can co-exist in package architecture, and the namespace changes are done in order to avoid any conflicts. `Microsoft.Data.SqlClient` is not a repalcement over `System.Data.SqlClient`, but is a separate library in itself.

However, when using either of 2 in your application, you cannot cross-reference each other's objects or referenced objects. Hope that clears your doubts! :)
