### ISSUE TITLE
Can the SqlServerTransientExceptionDetector be moved to System.Data.SqlClient?

### ISSUE THREAD

**Issue by divega** [dotnet/SqlClient#39]
_From @avantida on October 18, 2018 8:17_

The [`SqlServerTransientExceptionDetector`](https://github.com/aspnet/EntityFrameworkCore/blob/3bc37f140fa2a91768c10dde2b3b6a3e2964f9bb/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs) class is really handy to detect if a Sql operation needs to be retried while building anything based on a SqlConnection.
It basically is the core component driving the [`SqlServerRetryingExecutionStrategy`](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs) of .NET EF Core. (which used to be the `AzureSqlExecutionStrategy` in EF)

This logic is sort of replicated also in the [Enterprise Library Transient Fault Handling Application Block](https://github.com/Chavoshi/EnterpriseLibrary.NetCore/blob/75b236b41efed24bc10dd9f16386d97b27573325/Source/Transient%20Fault%20Handling%20Application%20Block/TransientFaultHandling.Data/SqlDatabaseTransientErrorDetectionStrategy.cs) and then again even in the [Elastic database tools for Azure SQL Database](https://github.com/Azure/elastic-db-tools/blob/master/Src/ElasticScale.Client/ElasticScale.Common/TransientFaultHandling/Implementation/SqlDatabaseTransientErrorDetectionStrategy.cs)

Moving this code 'upstream' would aid a lot to enable reliable operation with Azure Sql with any of the SQL compatible [ .NET Core Data Access](https://blogs.msdn.microsoft.com/dotnet/2016/11/09/net-core-data-access/) tools out there.

Today we're not _[falling in the pit of success](https://blog.codinghorror.com/falling-into-the-pit-of-success/)_ to run our code on Azure. (We're using Dapper @NickCraver )

_Copied from original issue: aspnet/EntityFrameworkCore#13665_

**Comment by Plasma** [comment]
_Really_ supportive of having this in the base package (or an extension package) with a production-ready integration working. The guidance on Azure website and MSDN is a total mess.

* There was originally reference to TOPAZ library and ReliableSqlConnection, that is now obsolete.

* The Azure docs provide a range of error codes to be retried, https://docs.microsoft.com/en-us/azure/sql-database/troubleshoot-connectivity-issues-microsoft-azure-sql-database#transient-fault-error-messages with no clear production-ready strategy to handle them (just wrap connection.Open? What about command execution? What about pooled connections?).

* As mentioned in this ticket, there are multiple implementations of the same logic, but are tied to the higher-level frameworks (Elastic pools, EF) instead of being based on the low-level client

* When SqlConnection was updated to support retries, it was flagged as the replacement of ReliableSqlConnection, but it doesn't actually work well, so back to square one.

Any suggestions about where and how the retry logic should be placed for production-ready code would be appreciated, but going forward, this being built-in to the package itself would be ideal.

**Comment by scoriani** [comment]
There's work going on for this topic, see this PR: [https://github.com/dotnet/SqlClient/pull/307]

**Comment by Wraith2** [comment]
> When SqlConnection was updated to support retries, it was flagged as the replacement of ReliableSqlConnection, but it doesn't actually work well,

Can you expand on this? If there is already something in the library that's supposed to do the job but doesn't work i think it shoould be fixed if possible.

**Comment by scoriani** [comment]
Topaz (a.k.a. Transient Fault Handling Application Block) is not maintained anymore since quite some time and has been discontinued. Plus, the need for having retry logic capabilities embedded in client drivers is also helping customers with legacy apps that can't/don't want to change their codebase.

**Comment by ErikEJ** [comment]
@Wraith2 I guess it is something like this (a moving target) https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs

**Comment by Plasma** [comment]
> > When SqlConnection was updated to support retries, it was flagged as the replacement of ReliableSqlConnection, but it doesn't actually work well,
> 
> Can you expand on this? If there is already something in the library that's supposed to do the job but doesn't work i think it shoould be fixed if possible.

Hi @Wraith2 thanks for your interest. 

1) Here's some example guidance:

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-issues#net-sqlconnection-parameters-for-connection-retry

Note the discussion about using the ConnectRetryCount/Interval system.

This doesn't seem to be useful in Azure, we still get these errors:

```
SqlException: Database 'xxx on server 'xxx' is not currently available. Please retry the connection later. If the problem persists, contact customer support, and provide them the session tracing ID of 'xxx'. 
```

```
SqlException: Cannot open database "xxx" requested by the login. The login failed.Login failed for user 'xxx'. A severe error occurred on the current command. The results, if any, should be discarded.
```

```
SqlException: A transport-level error has occurred when sending the request to the server. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.) 
```

These all happen during failover/reconfiguration/behind-the-scenes events in Azure.

The "The login failed" error for example is due to the temporarily moment there is no primary replica during a failover, etc.

All of these errors are _frequent_ for a customer of Azure. Its really demoralizing. This is more of a criticism to Azure SQL, but as SqlConnection is the only place we can mitigate it, its depressingly difficult to work with.

We've been using ReliableSqlConnection from TOPAZ library for a few years which has shielded us from most of these, but as it is obsolete (and means we can't use async queries) we want to move away from it.

2) Second, I _think_ this only handles connections -- and won't do anything for mid-command execution, which can still error. TOPAZ library handled mid-flight query retries, so SqlClient/SqlConnection should too.

**Comment by avantida** [comment]
I'd like to revive this topic again, as we have been experiencing some issues with a 3rd party library, that is depending on SqlClient, but again is not Azure aware.

Also, I see there is another case added to the `SqlServerTransientExceptionDetector` class here: https://github.com/dotnet/efcore/commit/a094aba60b07ed02d2a005282859556208f6a8af

So EF will work, but raw SqlClient users (or any package using it) will need to find out the hard way.

**Comment by roji** [comment]
Note https://github.com/dotnet/runtime/issues/34817, which would introduce transient error categorization into ADO.NET itself, and allow SqlClient to internally determine which list of codes represent transient errors. I think that's the right way forward, rather then introducing an SqlClient-specific mechanism to do the same.

**Comment by cheenamalhotra** [comment]
As pointed by @roji above, https://github.com/dotnet/runtime/issues/34817 is going to supported with #649 and #648 to introduce APIs on SqlException to detect transient errors. Closing this discussion.
