### ISSUE TITLE
core2.0+ - NotificationAutoEnlist and its Absence

### ISSUE THREAD

**Issue by DiskElemental** [dotnet/SqlClient#393]
Hey All,

Apologies if this is a stupid question, but I only have a small amount of experience with interfacing Sql and C#. I am currently in the midst of uplifting a large quantity of code from net461 to Net Core 2.0, which includes dependencies on external libraries that I am unable to edit. One of these libraries attempts to set the NotificationAutoEnlist property on the SqlCommand to false--which results in an exception as the property no longer exists.

My current solution in the short term is to fork this repository, add the property back in and don't wire it up to anything. From my understanding, the property being set to false disables all functionality related to this boolean, therefore my workaround won't cause any greater issues within the context of this library.

My question then is twofold.

First, is my understanding of how this variable functions correct? Will adding the NotificationAutoEnlist boolean to the SqlCommand class causes problems when attempting to communicate with an external Sql server?

Second, are there plans to support this feature going forward, or is there some way to replicate the functionality in the current iteration of the library? My solution is obviously unsustainable, so if there's another way to replicate the functionality, I'll need to reach out to the library owners and present the alternative.

Thanks

**Comment by cheenamalhotra** [comment]
@DiskElemental 

I looked into it and as you mentioned "NotificationAutoEnlist" is default "true" and is used for transmitting messages/notifications for auto enlistement in .NET Framework.

The API internally uses "System.Runtime.Remoting.Messaging" APIs which are unfortunately not available in .NET Core since these events are available on Windows only.

To answer your 2 questions:
1. This property will not impact any communication with SQL Server, it's only used for sending messages by generating Events.
2. Since the core of this property is not supported in .NET Core, this property is less likely to be made available in .NET Core in future.

Application users may be disabling this property to enhance performance, but in .NET Core this is not needed.

**Comment by DiskElemental** [comment]
@cheenamalhotra Thank you. I'll pass that information along to the library's developers.

**Comment by cheenamalhotra** [comment]
You're welcome! 
I'll close the issue, you may reopen if you need any additional support.
