### ISSUE TITLE
Release notes on nuget.org

### ISSUE THREAD

**Issue by estensen** [dotnet/SqlClient#472]
### Is your feature request related to a problem? Please describe.
We use dependabot to upgrade our packages. When it creates a PR it also fetches the release notes if they are available on nuget.org. Because of that we don't have to go to releases on GitHub to see what changes. This would make the developer experience more smooth.

**Comment by cheenamalhotra** [comment]
Hi @estensen 

We kept the Release notes as forward link to avoid maintenance, but I don't think it will be very challenging to do if we also update the same along with changelog. We could consider this in our next preview release.

cc @David-Engel

**Comment by David-Engel** [comment]
What is the expected format for what goes on nuget.org? Browsing the top dozen or so packages, I see quite a variety, from zero release notes, to a single link, to some text with a link, and some with just a little text.

Note: Putting the contents of the release notes into the NuGet package would slow the release process because they would have to be complete before we could generate and test our final package and we wouldn't be able to update them afterwards (which we have had to do in the past). I would rather not tie the release package to finalized release notes like that.

**Comment by ErikEJ** [comment]
@David-Engel NuGet is working on enabling a readme.md to be included in your package! https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg

**Comment by cheenamalhotra** [comment]
Updated link to NuGet's support for Readme: https://github.com/NuGet/Home/wiki/Embedding-and-displaying-NuGet-READMEs

**Comment by JRahnama** [comment]
Closing this as the link has been updated.
