### ISSUE TITLE
Tech Empower Fortunes System.Data perf improvements

### ISSUE THREAD

**Issue by joshfree** [dotnet/SqlClient#66]
https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=fortune

Tracking issue for : 
1.	(~10%) Fix system.data.sqlclient!System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent on windows to cache the windows identity, or to mimic what Linux does
2. (~4%) There are hot locks in system.data.sqlclient 
a.	(2.7%) system.data.sqlclient!System.Data.ProviderBase.DbConnectionPool.PrepareConnection
b.	(.3%) system.data.sqlclient!System.Data.SqlClient.SqlConnection+OpenAsyncRetry.Retry
c.	(.5%) system.private.corelib!System.Threading.TimerQueueTimer.Change

@vancem @mikeharder

**Comment by mikeharder** [comment]
CC: @sebastienros

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by Wraith2** [comment]
I investigated and proposed changes to some of these items in https://github.com/dotnet/corefx/pull/37157 Ultimately it was closed because the benefits were small and only evident at startup, see the discussion for details.

The remaining item is to change PrepareConnection from locking to a RWLS which i've got a branch for but am waiting on code in this repo.

On linux identity is the hostname and this is safe because impersonation is not supported. On windows impersonation is possible and the hostname does not change when using it, so using th elinux mechanism on windows is insecure. The thing that can't be avoided is fetching the current user security identity. It might be possible to avoid some string allocations by caching the last identity seen and then comparing it to the fetched one.

**Comment by roji** [comment]
Am curious, is impersonation supported on .NET Core?

**Comment by Wraith2** [comment]
yes, https://apisof.net/catalog/System.Security.Principal.WindowsIdentity.RunImpersonated%3CT%3E(SafeAccessTokenHandle,Func%3CT%3E)

**Comment by roji** [comment]
That page is for .NET Framework but I can see impersonation seems to be available on [.NET Core too](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=netcore-3.0#System_Security_Principal_WindowsIdentity_RunImpersonated_Microsoft_Win32_SafeHandles_SafeAccessTokenHandle_System_Action_).

**Comment by Wraith2** [comment]
the page is just for the api, the comment says .net framework for some reason but the important part is the table of support at the bottom.

**Comment by roji** [comment]
Ah I see, thanks for pointing that out.

**Comment by David-Engel** [comment]
Closing as not planned.
