### ISSUE TITLE
could be remove the  depends  Microsoft.Identity and Microsoft.IdentityModel?

### ISSUE THREAD

**Issue by sgf** [dotnet/SqlClient#733]
the Old system.data.Sqlclient very clean.
but new  Microsoft.data.Sqlclient much depends .
or clould be let them as an optional ?

**Comment by Wraith2** [comment]
The System version depended on assemblies which were part of the runtime and because it was distributed as part of the runtime you could never be in a position where you needed to identify the full closure of dependencies. This library is standalone so the dependency tree has to contains a full closure. The dependency isn't new but you saw it as part of the runtime before.

**Comment by cheenamalhotra** [comment]
Hi @sgf 

There isn't a concept of Optional dependencies in NuGet packaging and these libraries are very much required for supporting Active Directory authentication modes.

**Comment by sgf** [comment]
@Wraith2 @cheenamalhotra  thanks reply
