### ISSUE TITLE
AppInsight Dependency doesn't seem to work

### ISSUE THREAD

**Issue by ewaldtlgs803** [dotnet/SqlClient#741]
According to the documentation of AI - https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query - using the Microsoft.Data.SqlClient NuGet library should be enough to see dependencies in AppInsights. However I don't see any showing up. 

If I use the TrackDependency method manually, they do appear, so the module seems to be installed correctly.

I am using v2.0.1

**Comment by ErikEJ** [comment]
You need to configure for logging SQL statements if you use ASP.NET Core and A.I. 2.14 or newer

**Comment by ewaldtlgs803** [comment]
I have it configured to capture the SQL Statements as far as I know. I have added this to the ApplictionInsights.config. 

  <TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
      <EnableSqlCommandTextInstrumentation>true</EnableSqlCommandTextInstrumentation>
    </Add>
  </TelemetryModules>

Before I moved to the Microsoft.Data.SqlClient NuGet library, I was using the System.Data.SqlClient, and at that time it was reporting the SQL Dependencies, but without the SQL statement.

**Comment by karinazhou** [comment]
Hi @ewaldtlgs803 , 

This issue is due to the new EventSource name of Microsoft.Data.SqlClient does not match the one used by DependencyCollector. You can refer to https://github.com/dotnet/SqlClient/issues/678 for more details.

Thanks,

**Comment by ewaldtlgs803** [comment]
Thanks @karinazhou, 

I have tried to downgrade to 1.1.3 to see if that would resolve the issue, but it did not. Did you expect that 1.1.3 would work if the EventSource is the issue?

Thanks.

**Comment by karinazhou** [comment]
@ewaldtlgs803  Yes, DependencyCollector should work with MDS 1.1.3 according to https://github.com/dotnet/SqlClient/issues/678 .  If that version doesn't work for you, there could be other reasons causing your issue. 

To further investigate it, could you please provide a standalone repo application so I can test it on my side?

Thanks,

**Comment by ewaldtlgs803** [comment]
[ConsoleApp4.zip](https://github.com/dotnet/SqlClient/files/5289521/ConsoleApp4.zip)

See attached very easy Console application.

**Comment by ewaldtlgs803** [comment]
@karinazhou do you have any update on this?

**Comment by karinazhou** [comment]
@ewaldtlgs803   Sorry, not yet. I was distracted by other issues. I will try your repo app sometime tomorrow.

**Comment by karinazhou** [comment]
@ewaldtlgs803   I tried your VB project and I can see the following message after I commented the following line:

`Telemetry.InstrumentationKey = "59b21c8c-b1d7-48f2-9b1a-f094d7faa0ef"`
`Telemetry.TrackDependency("MyDependency", "Some data", New DateTimeOffset(DateTime.Now), New TimeSpan(1, 0, 0), True)`

The message contains SQL statement:

```
Application Insights Telemetry (unconfigured): {"name":"AppDependencies","time":"2020-10-02T00:05:03.9637165Z","tags":{...},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":". | master","id":"c22c91e5a8351746","data":"SELECT COUNT(*) FROM sysObjects","duration":"00:00:00.1927676","success":true,"type":"SQL","target":". | master"}}}
```

This is with Microsoft.Data.SqlClient v1.1.3 from your ConsoleApp4.

When I switch to MDS v2.0.1, I couldn't see the Application Insights Telemetry anymore. One thing I noticed is that changing the driver version and sni version in the packages.config is not enough. It doesn't change the driver version in vbproj file. When you are saying 

`I have tried to downgrade to 1.1.3 to see if that would resolve the issue, but it did not. `

Could you double-check the driver you are loaded is actually from v1.1.3?

**Comment by ewaldtlgs803** [comment]
I did check, and my app did include the 1.1.3 version of Microsoft.Data.SqlClient.

The hint that you gave to look into the immediate window showed me that indeed in the sample app that I provided the dependency was logged. However, I was unable to see it in my own ApiController app. So I created another sample application that closer matches my scenario and in that app the Dependency is not logged, while the Event that I log manually is actually showing up

![image](https://user-images.githubusercontent.com/29872182/94905551-e96c8f00-0451-11eb-8cc6-b3e031f742d3.png)

![image](https://user-images.githubusercontent.com/29872182/94905693-233d9580-0452-11eb-8628-268a53786813.png)

[WebApplication1.zip](https://github.com/dotnet/SqlClient/files/5316888/WebApplication1.zip)

**Comment by karinazhou** [comment]
@ewaldtlgs803   Thank you for providing more details about this one.

I tried your `WebApplication1` on my side. As your description, I don't see any Application Insights Telemetry shown from the output window when debugging the `UnitTest1`. Even with System.Data.SqlClient, I couldn't see any Telemetry message shown. By manually adding the `Microsoft.ApplicationInsights.TelemetryClient.TrackDependency()`, the customized message can be seen. When I did my test, I added the `<EnableSqlCommandTextInstrumentation>true</EnableSqlCommandTextInstrumentation>` to your ApplicationInsights.config. I also tried to downgrade Microsoft.ApplicationInsights to 2.14.0 but there are no differences. 

As to the `FileNotFoundException`, it doesn't show up on my side. From the exception message, the `Microsoft.Data.SqlClient.resources` is suspicious to me. It should always look for `Microsoft.Data.SqlClient`. 

Because the first repo application you attached can generate the AppDepedency successfully, I would say the driver v1.1.3 is working as expected. You can also report this to [ApplicationInsights-dotnet](https://github.com/microsoft/ApplicationInsights-dotnet/issues) to get more help. 


Thanks,

**Comment by cheenamalhotra** [comment]
Closing issue as it comes from external component.
