### ISSUE TITLE
License for Microsoft.Data.SqlClient.SNI.runtime

### ISSUE THREAD

**Issue by bezysoftware** [dotnet/SqlClient#790]
Hi, is there any chance to change the license of the `Microsoft.Data.SqlClient.SNI.runtime` package to MIT? The reason I am asking is because the corporate I work in has a nuget proxy setup which filters access to packages to only those with allowed license (e.g. MIT). The "Microsoft .NET library" has quite a scary wording from the perspective of the company I work for and legal is unwilling to allow it. This has the consequence that we'll not be allowed to use e.g. EF Core v5 and others. Previous EF Core (or rather the older `Microsoft.Data.SqlClient`) has a dependency on `runtime.native.System.Data.SqlClient.sni` which has MIT license.

So overall, I am just curious why this particulour license was chosen for this package / if there is any chance to change it.

**Comment by cheenamalhotra** [comment]
cc @David-Engel

**Comment by David-Engel** [comment]
@bezysoftware The license was chosen because the code for that package is not open source. System.Data.SqlClient has a similar dependency on [an SNI native library with the same license](https://www.nuget.org/packages/runtime.win-x64.runtime.native.System.Data.SqlClient.sni/) and that is where Microsoft.Data.SqlClient inherited the dependency architecture and license from.

Which sections of the license are "scary"?

Note: You can avoid using that package if you are running on a non-Windows platform, or if you [set an app context switch on Windows](https://docs.microsoft.com/en-us/sql/connect/ado-net/appcontext-switches?view=sql-server-ver15#enabling-managed-networking-on-windows). Just be aware there are still some unresolved issues in the [managed SNI implementation in SqlClient around MARS and async](https://github.com/dotnet/SqlClient/issues?q=is%3Aissue+is%3Aopen+SNI+mars+async).

Regards,
David

**Comment by bezysoftware** [comment]
Thanks for the rationale. The legal haven't given me their full statement, but the main concern is 

"Data Collection. The software may collect information about you and your use of the software, and send that to Microsoft"

It looks like they will approve it after all though, after several months. Still, just wanted to make you aware there might be this concern with other companies, as was with us.

Re Context Switch, that doesn't help me when installing e.g. the EF Core v5 package though, does it? It cannot install without its dependencies, which are blocked by our proxy. Unless you're thinking manually referencing all its dlls manually which I would rather refrain from :)

**Comment by David-Engel** [comment]
Yeah, that section sounds scary but is standard boilerplate used across may MS products. It says "may" to cover all bases. That library definitely does NOT collect any data. I actually got that section changed from the stock legalese for other drivers for the same reasons you noted:

> DATA COLLECTION. Some features in the software may enable collection of data from users of your applications that access or use the software. If you use these features to enable data collection in your applications, you must comply with applicable law, including getting any required user consent, and maintain a prominent privacy policy that accurately informs users about how you use, collect, and share their data. You agree to comply with all applicable provisions of the Microsoft Privacy Statement at [https://go.microsoft.com/fwlink/?LinkId=521839].

I can look into updating this one, too.

The context switch won't help with blocking the dependencies from being installed, but it would keep it from being loaded/used is all.

Regards,
David

**Comment by cheenamalhotra** [comment]
License has been updated for Microsoft.Data.SqlClient.SNI **v3.0.0** and Microsoft.Data.SqlClient.SNI,runtime **v3.0.0**
