### ISSUE TITLE
ClickOnce Publish not working in .NET Core with Native SNI

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/SqlClient#810]
_Originally posted by @tatoadsl in https://github.com/dotnet/SqlClient/issues/441#issuecomment-729501673_

Hello,

This seems to be not solved or at least I can't make it work properly even trying the many workaround proposed here.
My project is .NET 5 using EF Core 5.0. The dependency uses is Microsoft.Data.SqlClient 2.0.1 and the files are not deployed with ClickOnce.

The problem is the same, can't find the Microsoft.Data.SqlClient.SNI.dll file as it is not copy to the deploy folder using ClickOnce publish.

Seems it is solved when targeting a .NET Framework project but not when it is with a .NET Core project.

Any expectation of a solution for this. Now that ClickOnce is avaiable for .NET Core projects can't be deploy properly because this issue.

Thanks.

PD: Not sure if this was the right place to comment on this or better to pen a new issue.

**Comment by cheenamalhotra** [comment]
@tatoadsl 

I've opened a new ticked to investigate this issue, to track well.
Will post here when I have some update!

**Comment by tatoadsl** [comment]
Thank you so much @cheenamalhotra . I invistigate more to try to find out if it is a package problem or not and I find out that could be maybe a ClickOnce itself problem under .NET Core and .NET 5.0

Find out other dependencies are having issues too when instead of using EF Core for SQL Server I tried EF Core for SQLite and also failed on deploy some dependencies of the package.

So at this point I'm not sure if it is ClickOnce itself or the package, but thanks for looking into it.

**Comment by jjxtra** [comment]
Issue also exists for single file .net 5 builds regardless of if click once is used

**Comment by cheenamalhotra** [comment]
Related issue: https://github.com/dotnet/runtime/issues/44602

**Comment by David-Engel** [comment]
Could not repro by publishing ClickOnce app with latest net6 version of EF Core. Files are deployed in runtimes folder. Closing as no longer repro.
