### ISSUE TITLE
System.Data.SqlClient.SqlConnection does not roll back open transaction on dispose

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/SqlClient#84]
SQL Server version is 2014 if it matters. Trivial reproduction causes timeout unless ;pooling=false is appended to the connection string.

```
    using System;
    using System.Data;
    using System.Data.SqlClient;

    /*
    CREATE TABLE Scratch (ID INTEGER NOT NULL);
    INSERT INTO Scratch VALUES (1);
    */

    namespace ConsoleApplication
    {
        public class Program
        {
            public static void Main(string[] args)
            {
                if (args.Length == 0) {
                    Console.WriteLine("Usage: dotnet disposeconnection.dll connectionstring");
                    return ;
                }
                using (var c1 = new SqlConnection(args[0]))
                {
                    c1.Open();
                    using (var c2 = new SqlConnection(args[0]))
                    {
                        c2.Open();
                        Exec(c2, "BEGIN TRANSACTION;");
                        Exec(c2, "UPDATE Scratch SET ID = 2;");
                    }
                    Exec(c1, "UPDATE Scratch SET ID=3;");
                }
            }

            private static void Exec(SqlConnection c, string s)
            {
                using (var m = c.CreateCommand())
                {
                    m.CommandText = s;
                    m.ExecuteNonQuery();
                }
            }
        }
    }
```

We got here through a much larger chunk of code handling thrown exceptions. We have no idea what the connection state is and it might have an executing data reader on it so we have no good way of passing the rollback command ourselves.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by bgribaudo** [comment]
@jhudsoncedaron 

>So how do you write a function that does not care if it is in a transaction or not to create a command?
>
>This is the reason we don't use the managed transaction API.

> We discovered that Connection.CreateCommand() returns a command that doesn't work if a transaction is open. It's easy enough to fix if you know you need to do this, but the fix code crashes if there is no transaction open. We have tons of helper functions that read stuff from the database that literally do not care if the caller opened a transaction or not.

Would https://github.com/dotnet/SqlClient/issues/28 resolve/bypass this issue?

**Comment by bgribaudo** [comment]
Thanks, @jhudsoncedaron! Maybe the fact that there are two of us who have an interest in #28 will get a little more traction under it. :-)

**Comment by jhudsoncedaron** [comment]
@bgribaudo : Don't hope too much. I've a pull request up for fixing a data loss bug that's probably going to be declined just because hitting the race condition is rare.

**Comment by bgribaudo** [comment]
@geleems 
>@jhudsoncedaron Could you provide a little more information about? :
>>a function that does not care if it is in a transaction or not to create a command
>
>In our understanding, if there is a function that creates a command without knowing if it is in a transaction or not, then the caller of the function should manage the transaction flow.

Agreed! The challenge is puling this off when `CreateCommand()` is used. 

Let's say I have a caller which manages transactions (as you describe). At certain points, this caller invokes other, low-level functions, passing them a reference to the db connection. These functions may choose to execute commands on that connection, creating those commands using `CreateCommand()`. These commands are transaction agnoistic--they don't modify the transaction state (no begins, rollbacks or commits) and don't care whether they are in a transaction. So far, this sounds good, and maintains separation of responsivities (caller handles transactions, low-level methods handle details in a transaction-agnostic way). 

The catch is that it doesn't work at the technical level with managed transactions. :-(

If the caller uses managed transactions, command created by those other functions using `CreateCommand()` will error because they haven't been associated with the open transaction. Either those low-level functions need to be passed a reference to the managed transaction (so that those functions, which are supposed to be transaction-agnostic can set the appropriate transaction property on each command they create) or the caller needs to use T-SQL to manage transactions. Neither option is preferable.

Something like the proposal in #28 would resolve this.

**Comment by cheenamalhotra** [comment]
As explained in https://github.com/dotnet/SqlClient/issues/84#issuecomment-298121435 by @geleems this is expected behavior if SqlClient is not managing transactions in pooled connection scenario.

Closing this issue as not a bug in driver.
